import { BuildingCategory, CityMetrics, CityBuilding } from '../types';

export interface BuildingTypeDefinition {
  id: string;
  nameRo: string;
  nameEn: string;
  category: BuildingCategory;
  baseCost: number; // Cost in ByteCoins
  descriptionRo: string;
  descriptionEn: string;
  icon: string;
  badgeLabel?: string;
  accentColor: string; // Tailwind border/glow color
  bgGradient: string;
  levels: {
    level: number;
    titleRo: string;
    titleEn: string;
    cost: number;
    computingPowerTFlops: number;
    cloudStoragePB: number;
    bandwidthTbps: number;
    ecoScore: number;
    securityRating: number;
    populationBonus: number;
    icon: string;
    descRo: string;
  }[];
}

export const BUILDING_CATALOG: BuildingTypeDefinition[] = [
  // ==================== 1. COMPUTING & AI ====================
  {
    id: 'datacenter',
    nameRo: 'Centrul de Date Cloud',
    nameEn: 'Cloud Data Center',
    category: 'computing',
    baseCost: 80,
    descriptionRo: 'Inima orașului: găzduiește servere de mare viteză și stocare securizată.',
    descriptionEn: 'The heartbeat of your city: hosts high-speed servers and cloud storage.',
    icon: '🏢',
    accentColor: 'border-cyan-400 text-cyan-300 shadow-cyan-500/40',
    bgGradient: 'from-cyan-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Mini Server Rack 1U',
        titleEn: '1U Server Rack',
        cost: 80,
        computingPowerTFlops: 25,
        cloudStoragePB: 5,
        bandwidthTbps: 2,
        ecoScore: 5,
        securityRating: 10,
        populationBonus: 50,
        icon: '🗄️',
        descRo: 'Un rack de servere compact pentru servicii de bază.',
      },
      {
        level: 2,
        titleRo: 'Centru de Date Enterprise',
        titleEn: 'Enterprise Data Facility',
        cost: 160,
        computingPowerTFlops: 75,
        cloudStoragePB: 20,
        bandwidthTbps: 8,
        ecoScore: 10,
        securityRating: 25,
        populationBonus: 150,
        icon: '🏢',
        descRo: 'Săli mari climatizate cu stocare redundantă RAID.',
      },
      {
        level: 3,
        titleRo: 'Mega Cluster Cloud Național',
        titleEn: 'National Cloud Cluster',
        cost: 320,
        computingPowerTFlops: 200,
        cloudStoragePB: 60,
        bandwidthTbps: 25,
        ecoScore: 15,
        securityRating: 45,
        populationBonus: 350,
        icon: '🏬',
        descRo: 'Cluster multi-regiune cu backup în timp real.',
      },
      {
        level: 4,
        titleRo: 'Hub Supracomputerizat Global',
        titleEn: 'Global Supercomputing Hub',
        cost: 600,
        computingPowerTFlops: 500,
        cloudStoragePB: 180,
        bandwidthTbps: 70,
        ecoScore: 25,
        securityRating: 70,
        populationBonus: 800,
        icon: '🏛️',
        descRo: 'Infrastructură hiperscalabilă alimentată cu răcire lichidă.',
      },
      {
        level: 5,
        titleRo: 'Quantum Hyper-Cluster 2099',
        titleEn: 'Quantum Hyper-Cluster 2099',
        cost: 1200,
        computingPowerTFlops: 1500,
        cloudStoragePB: 600,
        bandwidthTbps: 200,
        ecoScore: 40,
        securityRating: 100,
        populationBonus: 2000,
        icon: '🌌',
        descRo: 'Rețea cuantică completă capabilă de procesare la viteza luminii!',
      },
    ],
  },
  {
    id: 'ai_lab',
    nameRo: 'Laboratorul Neural AI',
    nameEn: 'AI Neural Lab',
    category: 'computing',
    baseCost: 120,
    descriptionRo: 'Antrenează modele de inteligență artificială pentru roboței și asistenți.',
    descriptionEn: 'Trains artificial intelligence models for autonomous robots.',
    icon: '🧠',
    accentColor: 'border-purple-400 text-purple-300 shadow-purple-500/40',
    bgGradient: 'from-purple-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Atelier de Algoritmi de Bază',
        titleEn: 'Basic Algorithms Studio',
        cost: 120,
        computingPowerTFlops: 40,
        cloudStoragePB: 2,
        bandwidthTbps: 3,
        ecoScore: 5,
        securityRating: 15,
        populationBonus: 80,
        icon: '💡',
        descRo: 'Primele scripturi de logică și recunoaștere a tiparelor.',
      },
      {
        level: 2,
        titleRo: 'Cluster Deep Learning',
        titleEn: 'Deep Learning Cluster',
        cost: 240,
        computingPowerTFlops: 120,
        cloudStoragePB: 10,
        bandwidthTbps: 10,
        ecoScore: 10,
        securityRating: 30,
        populationBonus: 220,
        icon: '🧠',
        descRo: 'Rețele neuronale cu milioane de parametri pentru asistentul Arky.',
      },
      {
        level: 3,
        titleRo: 'Centru de Viziune Computațională',
        titleEn: 'Computer Vision Complex',
        cost: 480,
        computingPowerTFlops: 300,
        cloudStoragePB: 35,
        bandwidthTbps: 30,
        ecoScore: 20,
        securityRating: 50,
        populationBonus: 500,
        icon: '👁️',
        descRo: 'Camere inteligente și senzori urbani pentru siguranța cetățenilor.',
      },
      {
        level: 4,
        titleRo: 'Institutul de Robotică Autonomă',
        titleEn: 'Autonomous Robotics Institute',
        cost: 900,
        computingPowerTFlops: 750,
        cloudStoragePB: 100,
        bandwidthTbps: 80,
        ecoScore: 30,
        securityRating: 80,
        populationBonus: 1200,
        icon: '🤖',
        descRo: 'Roboței autonomi care curăță și optimizează metropola.',
      },
      {
        level: 5,
        titleRo: 'Superinteligența Arky Prime',
        titleEn: 'Arky Prime Superintelligence',
        cost: 1600,
        computingPowerTFlops: 2200,
        cloudStoragePB: 400,
        bandwidthTbps: 250,
        ecoScore: 50,
        securityRating: 100,
        populationBonus: 3000,
        icon: '✨',
        descRo: 'O minte digitală binevoitoare care coordonează tot traficul și datele!',
      },
    ],
  },
  {
    id: 'chip_foundry',
    nameRo: 'Fabrica de Microcipuri & Siliciu',
    nameEn: 'Microchip & Silicon Foundry',
    category: 'computing',
    baseCost: 150,
    descriptionRo: 'Produce procesoare CPU, plăci grafice GPU și cipuri de memorie de ultimă generație.',
    descriptionEn: 'Manufactures next-gen CPUs, GPUs, and high-speed memory chips.',
    icon: '🔬',
    accentColor: 'border-amber-400 text-amber-300 shadow-amber-500/40',
    bgGradient: 'from-amber-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Atelier de Circuite Imprimate (PCB)',
        titleEn: 'PCB Printed Circuit Workshop',
        cost: 150,
        computingPowerTFlops: 30,
        cloudStoragePB: 3,
        bandwidthTbps: 1,
        ecoScore: 5,
        securityRating: 10,
        populationBonus: 60,
        icon: '🔌',
        descRo: 'Linii simple de asamblare a plăcilor de bază.',
      },
      {
        level: 2,
        titleRo: 'Laminator de Siliciu 14nm',
        titleEn: '14nm Silicon Fabrication',
        cost: 280,
        computingPowerTFlops: 90,
        cloudStoragePB: 8,
        bandwidthTbps: 5,
        ecoScore: 10,
        securityRating: 20,
        populationBonus: 180,
        icon: '💾',
        descRo: 'Cipuri rapide pentru calculatoarele din școli.',
      },
      {
        level: 3,
        titleRo: 'Fabrica Nanometrică 3nm EUV',
        titleEn: '3nm EUV Nano Foundry',
        cost: 550,
        computingPowerTFlops: 250,
        cloudStoragePB: 25,
        bandwidthTbps: 18,
        ecoScore: 20,
        securityRating: 40,
        populationBonus: 400,
        icon: '🔬',
        descRo: 'Litografie ultraviolet extremă cu miliarde de tranzistori.',
      },
      {
        level: 4,
        titleRo: 'Combinat de Grafen & Fotonice',
        titleEn: 'Graphene & Photonics Plant',
        cost: 1000,
        computingPowerTFlops: 650,
        cloudStoragePB: 80,
        bandwidthTbps: 55,
        ecoScore: 35,
        securityRating: 70,
        populationBonus: 950,
        icon: '💎',
        descRo: 'Procesoare fotonice care lucrează cu raze laser în loc de electricitate.',
      },
      {
        level: 5,
        titleRo: 'Sinteză Cuantică Atomică',
        titleEn: 'Atomic Quantum Synthesizer',
        cost: 1800,
        computingPowerTFlops: 1800,
        cloudStoragePB: 300,
        bandwidthTbps: 160,
        ecoScore: 55,
        securityRating: 95,
        populationBonus: 2500,
        icon: '⚛️',
        descRo: 'Cipuri asamblate atom cu atom cu performanțe uluitoare!',
      },
    ],
  },

  // ==================== 2. NETWORKING & TELECOM ====================
  {
    id: '5g_tower',
    nameRo: 'Turnul Satelit 5G / 6G',
    nameEn: '5G / 6G Satellite Tower',
    category: 'networking',
    baseCost: 70,
    descriptionRo: 'Transmite date wireless cu latență de sub 1 milisecundă în tot orașul.',
    descriptionEn: 'Broadcasts ultra-low latency wireless data across the metropolis.',
    icon: '📡',
    accentColor: 'border-teal-400 text-teal-300 shadow-teal-500/40',
    bgGradient: 'from-teal-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Pilon Wi-Fi 6 Urban',
        titleEn: 'Urban Wi-Fi 6 Mast',
        cost: 70,
        computingPowerTFlops: 5,
        cloudStoragePB: 1,
        bandwidthTbps: 10,
        ecoScore: 10,
        securityRating: 15,
        populationBonus: 70,
        icon: '📶',
        descRo: 'Acoperire de cartier pentru dispozitive mobile.',
      },
      {
        level: 2,
        titleRo: 'Antenă Rețea 5G Ultra-Wide',
        titleEn: '5G Ultra-Wide Tower',
        cost: 140,
        computingPowerTFlops: 15,
        cloudStoragePB: 4,
        bandwidthTbps: 30,
        ecoScore: 15,
        securityRating: 30,
        populationBonus: 200,
        icon: '📡',
        descRo: 'Viteze de descărcare de 10 Gbps pe fiecare stradă.',
      },
      {
        level: 3,
        titleRo: 'Releu Holografic 6G Terahertz',
        titleEn: '6G Terahertz Holographic Relay',
        cost: 300,
        computingPowerTFlops: 45,
        cloudStoragePB: 12,
        bandwidthTbps: 80,
        ecoScore: 25,
        securityRating: 50,
        populationBonus: 450,
        icon: '🗼',
        descRo: 'Permite transmisii holografice live între toți elevii.',
      },
      {
        level: 4,
        titleRo: 'Constelație Satelitară Laser',
        titleEn: 'Laser Satellite Constellation',
        cost: 580,
        computingPowerTFlops: 110,
        cloudStoragePB: 35,
        bandwidthTbps: 200,
        ecoScore: 35,
        securityRating: 75,
        populationBonus: 1000,
        icon: '🛰️',
        descRo: 'Legături optice directe prin sateliți de orbită joasă.',
      },
      {
        level: 5,
        titleRo: 'Rețea Neuronală Planetară 7G',
        titleEn: '7G Planetary Neural Grid',
        cost: 1100,
        computingPowerTFlops: 300,
        cloudStoragePB: 100,
        bandwidthTbps: 550,
        ecoScore: 50,
        securityRating: 100,
        populationBonus: 2400,
        icon: '🌐',
        descRo: 'Internet instantaneu fără fire pe tot globul!',
      },
    ],
  },
  {
    id: 'fiber_hub',
    nameRo: 'Nodul Central de Fibră Optică',
    nameEn: 'Central Optical Fiber Hub',
    category: 'networking',
    baseCost: 95,
    descriptionRo: 'Magistrala de mare viteză prin cabluri subterane de sticlă ce transportă fascicule laser.',
    descriptionEn: 'High-speed backbone carrying laser data packets through glass conduits.',
    icon: '🌐',
    accentColor: 'border-sky-400 text-sky-300 shadow-sky-500/40',
    bgGradient: 'from-sky-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Nod de Joncțiune Local',
        titleEn: 'Local Junction Box',
        cost: 95,
        computingPowerTFlops: 10,
        cloudStoragePB: 2,
        bandwidthTbps: 15,
        ecoScore: 10,
        securityRating: 15,
        populationBonus: 60,
        icon: '🔌',
        descRo: 'Cabluri din fibră monomod pentru conexiunea la server.',
      },
      {
        level: 2,
        titleRo: 'Switch Backbone 100Gbps',
        titleEn: '100Gbps Backbone Switch',
        cost: 190,
        computingPowerTFlops: 25,
        cloudStoragePB: 6,
        bandwidthTbps: 45,
        ecoScore: 15,
        securityRating: 30,
        populationBonus: 180,
        icon: '🌐',
        descRo: 'Rutează terabiți de date școlare fără întârziere.',
      },
      {
        level: 3,
        titleRo: 'Stație de Cabluri Submarine',
        titleEn: 'Subsea Cable Landing Station',
        cost: 390,
        computingPowerTFlops: 70,
        cloudStoragePB: 20,
        bandwidthTbps: 120,
        ecoScore: 25,
        securityRating: 50,
        populationBonus: 400,
        icon: '🌊',
        descRo: 'Conectează metropola cu marile continente ale planetei.',
      },
      {
        level: 4,
        titleRo: 'Autostradă Fotonice de Date',
        titleEn: 'Photonic Data Highway',
        cost: 750,
        computingPowerTFlops: 180,
        cloudStoragePB: 60,
        bandwidthTbps: 300,
        ecoScore: 35,
        securityRating: 75,
        populationBonus: 900,
        icon: '⚡',
        descRo: 'Impulsuri laser multiplexate pe 256 de lungimi de undă.',
      },
      {
        level: 5,
        titleRo: 'Nod de Teleportare Cuantică',
        titleEn: 'Quantum Entanglement Gateway',
        cost: 1400,
        computingPowerTFlops: 500,
        cloudStoragePB: 200,
        bandwidthTbps: 850,
        ecoScore: 50,
        securityRating: 100,
        populationBonus: 2200,
        icon: '🌀',
        descRo: 'Transfer de date cu latență zero prin inseparabilitate cuantică!',
      },
    ],
  },

  // ==================== 3. ECO ENERGY & POWER ====================
  {
    id: 'solar_matrix',
    nameRo: 'Matricea Solară Inteligentă',
    nameEn: 'Smart Solar Matrix',
    category: 'energy',
    baseCost: 65,
    descriptionRo: 'Energie 100% verde și regenerabilă pentru alimentarea întregii infrastructuri TIC.',
    descriptionEn: '100% clean, green renewable energy powering your entire tech grid.',
    icon: '☀️',
    accentColor: 'border-yellow-400 text-yellow-300 shadow-yellow-500/40',
    bgGradient: 'from-yellow-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Acoperișuri Solare Fotovoltaice',
        titleEn: 'Rooftop Solar Panels',
        cost: 65,
        computingPowerTFlops: 5,
        cloudStoragePB: 0,
        bandwidthTbps: 0,
        ecoScore: 25,
        securityRating: 10,
        populationBonus: 40,
        icon: '🔅',
        descRo: 'Panouri din siliciu monocristalin cu randament bun.',
      },
      {
        level: 2,
        titleRo: 'Parc Solar Urmăritor de Soare',
        titleEn: 'Sun-Tracking Solar Array',
        cost: 130,
        computingPowerTFlops: 15,
        cloudStoragePB: 2,
        bandwidthTbps: 2,
        ecoScore: 50,
        securityRating: 20,
        populationBonus: 120,
        icon: '☀️',
        descRo: 'Panouri rotative care urmăresc poziția soarelui pe cer.',
      },
      {
        level: 3,
        titleRo: 'Celule Solare cu Perovskit',
        titleEn: 'Perovskite High-Yield Cells',
        cost: 270,
        computingPowerTFlops: 40,
        cloudStoragePB: 5,
        bandwidthTbps: 5,
        ecoScore: 75,
        securityRating: 35,
        populationBonus: 300,
        icon: '🌞',
        descRo: 'Eficiență de 45% și baterii din grafen pentru stocare nocturnă.',
      },
      {
        level: 4,
        titleRo: 'Turn Solar Termic Concentrat',
        titleEn: 'Concentrated Solar Tower',
        cost: 520,
        computingPowerTFlops: 100,
        cloudStoragePB: 15,
        bandwidthTbps: 15,
        ecoScore: 90,
        securityRating: 55,
        populationBonus: 650,
        icon: '🗼',
        descRo: 'Oglinzi heliostatice ce încălzesc săruri topite pentru energie 24/7.',
      },
      {
        level: 5,
        titleRo: 'Colector Solar Spațial Orbital',
        titleEn: 'Orbital Space Solar Array',
        cost: 1050,
        computingPowerTFlops: 250,
        cloudStoragePB: 40,
        bandwidthTbps: 40,
        ecoScore: 100,
        securityRating: 80,
        populationBonus: 1600,
        icon: '🪐',
        descRo: 'Culege energia soarelui din spațiu și o transmite prin microunde curate!',
      },
    ],
  },
  {
    id: 'fusion_reactor',
    nameRo: 'Reactorul de Fuziune Curată',
    nameEn: 'Clean Fusion Reactor',
    category: 'energy',
    baseCost: 200,
    descriptionRo: 'Cea mai avansată sursă de energie a viitorului: recreează puterea unei stele.',
    descriptionEn: 'The ultimate future energy source: creates star-power with zero pollution.',
    icon: '⚛️',
    accentColor: 'border-emerald-400 text-emerald-300 shadow-emerald-500/40',
    bgGradient: 'from-emerald-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Camera Magnetică Tokamak Beta',
        titleEn: 'Tokamak Magnetic Chamber',
        cost: 200,
        computingPowerTFlops: 50,
        cloudStoragePB: 5,
        bandwidthTbps: 5,
        ecoScore: 30,
        securityRating: 25,
        populationBonus: 100,
        icon: '🧲',
        descRo: 'Confinare magnetică a plasmei de hidrogen.',
      },
      {
        level: 2,
        titleRo: 'Reactor Stellerator de Mare Putere',
        titleEn: 'High-Output Stellarator',
        cost: 380,
        computingPowerTFlops: 150,
        cloudStoragePB: 15,
        bandwidthTbps: 15,
        ecoScore: 60,
        securityRating: 45,
        populationBonus: 280,
        icon: '⚛️',
        descRo: 'Bobine supraconductoare complexe pentru fuziune stabilă continuă.',
      },
      {
        level: 3,
        titleRo: 'Centrală de Fuziune Heliu-3',
        titleEn: 'Helium-3 Fusion Powerplant',
        cost: 720,
        computingPowerTFlops: 380,
        cloudStoragePB: 40,
        bandwidthTbps: 40,
        ecoScore: 85,
        securityRating: 70,
        populationBonus: 600,
        icon: '🔋',
        descRo: 'Combustibil ecologic din izotopi curați, fără deșeuri radioactive.',
      },
      {
        level: 4,
        titleRo: 'Inima Stelară Miniaturizată',
        titleEn: 'Miniaturized Stellar Core',
        cost: 1300,
        computingPowerTFlops: 900,
        cloudStoragePB: 120,
        bandwidthTbps: 100,
        ecoScore: 98,
        securityRating: 90,
        populationBonus: 1400,
        icon: '⭐',
        descRo: 'Alimentează supercomputerele orașului cu energie nelimitată!',
      },
      {
        level: 5,
        titleRo: 'Generator Antimaterie Cuantică',
        titleEn: 'Quantum Antimatter Engine',
        cost: 2400,
        computingPowerTFlops: 2500,
        cloudStoragePB: 350,
        bandwidthTbps: 300,
        ecoScore: 100,
        securityRating: 100,
        populationBonus: 3500,
        icon: '💎',
        descRo: 'Reacții de anihilare controlată ce deschid porțile spre era galactică!',
      },
    ],
  },

  // ==================== 4. EDUCATION & CULTURE ====================
  {
    id: 'robotics_academy',
    nameRo: 'Academia de Robotică & TIC Arky',
    nameEn: 'Arky ICT & Robotics Academy',
    category: 'education',
    baseCost: 110,
    descriptionRo: 'Școala viitorului: unde elevii și roboțeii învață algoritmi, tastare și hardware.',
    descriptionEn: 'The school of the future: where kids and robots master coding and IT.',
    icon: '🎓',
    accentColor: 'border-indigo-400 text-indigo-300 shadow-indigo-500/40',
    bgGradient: 'from-indigo-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Laborator de Informatică Școlar',
        titleEn: 'School Computer Lab',
        cost: 110,
        computingPowerTFlops: 15,
        cloudStoragePB: 3,
        bandwidthTbps: 5,
        ecoScore: 15,
        securityRating: 20,
        populationBonus: 150,
        icon: '🏫',
        descRo: 'Monitoare color, tastaturi mecanice și lecții interactive.',
      },
      {
        level: 2,
        titleRo: 'Atelier de Programare Scratch & Blockly',
        titleEn: 'Scratch Coding Workshop',
        cost: 220,
        computingPowerTFlops: 50,
        cloudStoragePB: 10,
        bandwidthTbps: 15,
        ecoScore: 25,
        securityRating: 40,
        populationBonus: 350,
        icon: '🧩',
        descRo: 'Elevii creează jocuri și animații cu bucle și variabile.',
      },
      {
        level: 3,
        titleRo: 'Campus Universitar de Cibernetică',
        titleEn: 'Cybernetics University Campus',
        cost: 450,
        computingPowerTFlops: 130,
        cloudStoragePB: 30,
        bandwidthTbps: 40,
        ecoScore: 40,
        securityRating: 65,
        populationBonus: 750,
        icon: '🎓',
        descRo: 'Amfiteatre moderne cu proiecții 3D și simulatoare de rețea.',
      },
      {
        level: 4,
        titleRo: 'Institutul Național de Inovare TIC',
        titleEn: 'National ICT Innovation Institute',
        cost: 850,
        computingPowerTFlops: 320,
        cloudStoragePB: 80,
        bandwidthTbps: 90,
        ecoScore: 60,
        securityRating: 85,
        populationBonus: 1600,
        icon: '🏛️',
        descRo: 'Cercetare în securitate cibernetică și sisteme de operare rapide.',
      },
      {
        level: 5,
        titleRo: 'Academia Intergalactică a Codului',
        titleEn: 'Intergalactic Coding Academy',
        cost: 1500,
        computingPowerTFlops: 800,
        cloudStoragePB: 250,
        bandwidthTbps: 220,
        ecoScore: 80,
        securityRating: 100,
        populationBonus: 3200,
        icon: '👑',
        descRo: 'Pregătește cei mai buni campioni la olimpiadele internaționale de informatică!',
      },
    ],
  },
  {
    id: 'retro_museum',
    nameRo: 'Muzeul Calculatoarelor Retro',
    nameEn: 'Retro PC & Arcade Museum',
    category: 'education',
    baseCost: 85,
    descriptionRo: 'Păstrează vie istoria primelor computere, jocurilor arcade de epocă și dischetelor.',
    descriptionEn: 'Celebrates the history of vintage PCs, 8-bit arcade classics and floppy disks.',
    icon: '🕹️',
    accentColor: 'border-pink-400 text-pink-300 shadow-pink-500/40',
    bgGradient: 'from-pink-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Colecția de Dischete 3.5" & Benzi',
        titleEn: '3.5" Floppy Disk Gallery',
        cost: 85,
        computingPowerTFlops: 10,
        cloudStoragePB: 1,
        bandwidthTbps: 2,
        ecoScore: 10,
        securityRating: 10,
        populationBonus: 100,
        icon: '💾',
        descRo: 'Amintiri din anii \'80 cu calculatoare Felix și HC-85.',
      },
      {
        level: 2,
        titleRo: 'Sala de Jocuri Arcade 8-Bit',
        titleEn: '8-Bit Retro Arcade Hall',
        cost: 170,
        computingPowerTFlops: 30,
        cloudStoragePB: 4,
        bandwidthTbps: 6,
        ecoScore: 20,
        securityRating: 20,
        populationBonus: 250,
        icon: '🕹️',
        descRo: 'Cabinete arcade cu joystick-uri și monitoare CRT.',
      },
      {
        level: 3,
        titleRo: 'Pavilionul Primelor Supercomputere',
        titleEn: 'Early Supercomputers Pavilion',
        cost: 350,
        computingPowerTFlops: 80,
        cloudStoragePB: 12,
        bandwidthTbps: 15,
        ecoScore: 30,
        securityRating: 35,
        populationBonus: 550,
        icon: '📼',
        descRo: 'Modele legendare IBM, ENIAC și computere cu tuburi electronice.',
      },
      {
        level: 4,
        titleRo: 'Centrul de Arheologie Digitală',
        titleEn: 'Digital Archaeology Center',
        cost: 680,
        computingPowerTFlops: 200,
        cloudStoragePB: 35,
        bandwidthTbps: 40,
        ecoScore: 45,
        securityRating: 55,
        populationBonus: 1100,
        icon: '🏺',
        descRo: 'Restaurează cod sursă vechi și documente istorice scanate.',
      },
      {
        level: 5,
        titleRo: 'Panteonul Marilor Pionieri TIC',
        titleEn: 'Pantheon of ICT Pioneers',
        cost: 1250,
        computingPowerTFlops: 500,
        cloudStoragePB: 100,
        bandwidthTbps: 100,
        ecoScore: 60,
        securityRating: 80,
        populationBonus: 2200,
        icon: '🏛️',
        descRo: 'Statui holografice dedicate lui Alan Turing, Ada Lovelace și Grigore Moisil!',
      },
    ],
  },
  {
    id: 'cyber_park',
    nameRo: 'Parcul Ecologic Bioluminescent',
    nameEn: 'Bioluminescent Cyber Park',
    category: 'education',
    baseCost: 60,
    descriptionRo: 'Oază de natură cibernetică cu copaci iluminați și aer curat pentru locuitori.',
    descriptionEn: 'Cybernetic green oasis with glowing trees and fresh air for citizens.',
    icon: '🌳',
    accentColor: 'border-emerald-400 text-emerald-300 shadow-emerald-500/40',
    bgGradient: 'from-emerald-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Aleea Stejarilor Verzi',
        titleEn: 'Green Oak Promenade',
        cost: 60,
        computingPowerTFlops: 0,
        cloudStoragePB: 0,
        bandwidthTbps: 0,
        ecoScore: 40,
        securityRating: 10,
        populationBonus: 120,
        icon: '🌿',
        descRo: 'Spațiu de relaxare și aerisire naturală.',
      },
      {
        level: 2,
        titleRo: 'Grădina Senzorilor Inteligenți',
        titleEn: 'Smart Sensor Botanical Garden',
        cost: 120,
        computingPowerTFlops: 10,
        cloudStoragePB: 2,
        bandwidthTbps: 2,
        ecoScore: 70,
        securityRating: 20,
        populationBonus: 300,
        icon: '🌷',
        descRo: 'Irigare automată și flori cu lumină ambientală plăcută.',
      },
      {
        level: 3,
        titleRo: 'Pădurea de Bambus Fotonici',
        titleEn: 'Photonic Bamboo Forest',
        cost: 250,
        computingPowerTFlops: 25,
        cloudStoragePB: 5,
        bandwidthTbps: 5,
        ecoScore: 90,
        securityRating: 30,
        populationBonus: 600,
        icon: '🎋',
        descRo: 'Tulpini ce conduc lumina naturală direct în clădirile subterane.',
      },
      {
        level: 4,
        titleRo: 'Lacul de Apă Purificată Nano',
        titleEn: 'Nano-Purified Crystal Lake',
        cost: 500,
        computingPowerTFlops: 60,
        cloudStoragePB: 12,
        bandwidthTbps: 12,
        ecoScore: 98,
        securityRating: 50,
        populationBonus: 1250,
        icon: '💧',
        descRo: 'Purificatoare acvatice cu grafen ce asigură răcirea ecologică a serverelor.',
      },
      {
        level: 5,
        titleRo: 'Biosfera Eden 2099',
        titleEn: 'Eden 2099 Biosphere Dome',
        cost: 1000,
        computingPowerTFlops: 150,
        cloudStoragePB: 30,
        bandwidthTbps: 30,
        ecoScore: 100,
        securityRating: 75,
        populationBonus: 2600,
        icon: '🌴',
        descRo: 'O cupolă ecologică perfectă în care tehnologia și natura coexistă în armonie!',
      },
    ],
  },

  // ==================== 5. CYBER SECURITY & DEFENSE ====================
  {
    id: 'firewall_tower',
    nameRo: 'Turnul de Securitate Firewall',
    nameEn: 'Firewall Security Fortress',
    category: 'security',
    baseCost: 90,
    descriptionRo: 'Scutul de apărare al orașului împotriva atacurilor DDoS, phishing și intrușilor.',
    descriptionEn: 'City defense shield blocking DDoS attacks, phishing and cyber intrusions.',
    icon: '🛡️',
    accentColor: 'border-rose-400 text-rose-300 shadow-rose-500/40',
    bgGradient: 'from-rose-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Filtru de Pachete Binar',
        titleEn: 'Binary Packet Filter',
        cost: 90,
        computingPowerTFlops: 10,
        cloudStoragePB: 1,
        bandwidthTbps: 5,
        ecoScore: 10,
        securityRating: 30,
        populationBonus: 50,
        icon: '🧱',
        descRo: 'Verifică adresele IP și blochează porturile nesigure.',
      },
      {
        level: 2,
        titleRo: 'Bastion Criptografic AES-256',
        titleEn: 'AES-256 Crypto Bastion',
        cost: 180,
        computingPowerTFlops: 30,
        cloudStoragePB: 5,
        bandwidthTbps: 15,
        ecoScore: 15,
        securityRating: 55,
        populationBonus: 160,
        icon: '🔒',
        descRo: 'Criptează datele personale ale elevilor și profesorilor.',
      },
      {
        level: 3,
        titleRo: 'Sistem de Detecție a Intruziunilor (IDS)',
        titleEn: 'Intrusion Detection System',
        cost: 370,
        computingPowerTFlops: 80,
        cloudStoragePB: 15,
        bandwidthTbps: 40,
        ecoScore: 25,
        securityRating: 75,
        populationBonus: 420,
        icon: '🚨',
        descRo: 'Senzori AI care identifică atacurile înainte ca acestea să ajungă la servere.',
      },
      {
        level: 4,
        titleRo: 'Fortăreața Zero-Trust Cyber',
        titleEn: 'Zero-Trust Cyber Citadel',
        cost: 720,
        computingPowerTFlops: 220,
        cloudStoragePB: 45,
        bandwidthTbps: 100,
        ecoScore: 35,
        securityRating: 90,
        populationBonus: 950,
        icon: '🏰',
        descRo: 'Politici stricte de autentificare în doi pași pentru toți cetățenii.',
      },
      {
        level: 5,
        titleRo: 'Scutul Cuantic de Criptare Totală',
        titleEn: 'Quantum Total Encryption Aegis',
        cost: 1350,
        computingPowerTFlops: 600,
        cloudStoragePB: 130,
        bandwidthTbps: 250,
        ecoScore: 50,
        securityRating: 100,
        populationBonus: 2300,
        icon: '🛡️',
        descRo: 'Nicio amenințare cibernetică nu poate penetra metropola!',
      },
    ],
  },
  {
    id: 'antivirus_lab',
    nameRo: 'Centrul de Cercetare Antimalware',
    nameEn: 'Antimalware Research Center',
    category: 'security',
    baseCost: 100,
    descriptionRo: 'Izolează virușii în cutii de nisip (sandbox) și dezvoltă vaccinuri de securitate.',
    descriptionEn: 'Sandboxes viruses and engineers live security vaccines for data safety.',
    icon: '🧪',
    accentColor: 'border-red-400 text-red-300 shadow-red-500/40',
    bgGradient: 'from-red-950/80 via-slate-900 to-slate-950',
    levels: [
      {
        level: 1,
        titleRo: 'Laborator de Izolare Sandbox',
        titleEn: 'Sandbox Isolation Lab',
        cost: 100,
        computingPowerTFlops: 15,
        cloudStoragePB: 2,
        bandwidthTbps: 3,
        ecoScore: 10,
        securityRating: 25,
        populationBonus: 60,
        icon: '📦',
        descRo: 'Testează fișierele suspecte descărcate de pe Internet.',
      },
      {
        level: 2,
        titleRo: 'Bază de Semnături Virale',
        titleEn: 'Viral Signatures Database',
        cost: 200,
        computingPowerTFlops: 45,
        cloudStoragePB: 8,
        bandwidthTbps: 10,
        ecoScore: 15,
        securityRating: 50,
        populationBonus: 180,
        icon: '📜',
        descRo: 'Catalog cu milioane de mostre de troieni și adware neutralizați.',
      },
      {
        level: 3,
        titleRo: 'Centru de Răspuns la Incidente (CERT)',
        titleEn: 'Computer Emergency Response Team',
        cost: 420,
        computingPowerTFlops: 110,
        cloudStoragePB: 25,
        bandwidthTbps: 28,
        ecoScore: 25,
        securityRating: 70,
        populationBonus: 440,
        icon: '🚒',
        descRo: 'Echipă de intervenție rapidă 24/7 condusă de Arky.',
      },
      {
        level: 4,
        titleRo: 'Vânător Euristic Heuristic AI',
        titleEn: 'Heuristic AI Threat Hunter',
        cost: 800,
        computingPowerTFlops: 280,
        cloudStoragePB: 70,
        bandwidthTbps: 75,
        ecoScore: 35,
        securityRating: 88,
        populationBonus: 1050,
        icon: '🧬',
        descRo: 'Anticipează noile capcane și escrocherii înainte ca acestea să apară.',
      },
      {
        level: 5,
        titleRo: 'Sistem Imunitar Digital Autonom',
        titleEn: 'Autonomous Digital Immune System',
        cost: 1450,
        computingPowerTFlops: 750,
        cloudStoragePB: 200,
        bandwidthTbps: 190,
        ecoScore: 50,
        securityRating: 100,
        populationBonus: 2500,
        icon: '💎',
        descRo: 'Vindecă orice fișier corupt instantaneu și returnează datele intacte!',
      },
    ],
  },
];

// Calculate overall City Metrics from current buildings
export function calculateCityMetrics(buildings: Record<number, CityBuilding>): CityMetrics {
  let totalTFlops = 0;
  let totalPB = 0;
  let totalTbps = 0;
  let ecoPoints = 0;
  let securityPoints = 0;
  let population = 0;
  let buildingCount = 0;

  for (const b of Object.values(buildings)) {
    const def = BUILDING_CATALOG.find((d) => d.id === b.typeId);
    if (!def) continue;
    const lvlData = def.levels.find((l) => l.level === b.level) || def.levels[0];
    if (!lvlData) continue;

    buildingCount++;
    totalTFlops += lvlData.computingPowerTFlops;
    totalPB += lvlData.cloudStoragePB;
    totalTbps += lvlData.bandwidthTbps;
    ecoPoints += lvlData.ecoScore;
    securityPoints += lvlData.securityRating;
    population += lvlData.populationBonus;
  }

  // Base starter stats
  const baseTFlops = 10;
  const basePB = 1;
  const baseTbps = 1;
  const baseEco = 30;
  const baseSecurity = 20;
  const basePop = 100;

  const finalTFlops = baseTFlops + totalTFlops;
  const finalPB = basePB + totalPB;
  const finalTbps = baseTbps + totalTbps;
  const finalEco = Math.min(100, Math.round(baseEco + (buildingCount > 0 ? ecoPoints / Math.max(1, buildingCount) : 0)));
  const finalSec = Math.min(100, Math.round(baseSecurity + (buildingCount > 0 ? securityPoints / Math.max(1, buildingCount) : 0)));
  const finalPop = basePop + population;

  // City Score formula
  const cityScore = Math.round(
    finalTFlops * 1.5 +
    finalPB * 8 +
    finalTbps * 4 +
    finalEco * 15 +
    finalSec * 15 +
    finalPop * 0.5
  );

  // Mayor Rank Title
  let rankTitle = 'Primar Începător 🌱';
  if (cityScore >= 25000) {
    rankTitle = 'Arhitect Suprem Galactic 👑';
  } else if (cityScore >= 12000) {
    rankTitle = 'Guvernator Cibernetic 💎';
  } else if (cityScore >= 6000) {
    rankTitle = 'Maestru al Tehnologiei ⚡';
  } else if (cityScore >= 2500) {
    rankTitle = 'Inginer Urban TIC ⭐';
  } else if (cityScore >= 1000) {
    rankTitle = 'Planificator de Sisteme 🚀';
  }

  return {
    computingPowerTFlops: finalTFlops,
    cloudStoragePB: finalPB,
    bandwidthTbps: finalTbps,
    ecoScore: finalEco,
    securityRating: finalSec,
    totalPopulation: finalPop,
    cityScore,
    cityRankTitle: rankTitle,
  };
}
