import { ShopItem, EquippedItems, StudentInventory } from '../types';

export const DEFAULT_EQUIPPED: EquippedItems = {
  arkySkin: 'default',
  theme: 'default',
  title: '',
  avatarFrame: 'none',
};

export const DEFAULT_INVENTORY: StudentInventory = {
  ownedItemIds: [
    'skin_default',
    'theme_default',
    'frame_none',
    'title_cadet',
  ],
  openedMysteryBoxes: 0,
  unlockedMilestones: [],
};

export const SHOP_ITEMS: ShopItem[] = [
  // ==================== 1. SKINS PENTRU MASCOTA ARKY ====================
  {
    id: 'skin_default',
    category: 'arky_skin',
    nameRo: 'Arky Clasic',
    nameEn: 'Classic Arky',
    descRo: 'Aspectul prietenos original al robotului asistent TIC.',
    descEn: 'The original friendly look of the ICT companion robot.',
    icon: '🤖',
    price: 0,
    rarity: 'common',
    previewAsset: 'default',
  },
  {
    id: 'skin_cyber',
    category: 'arky_skin',
    nameRo: 'Cyber Arky 2099',
    nameEn: 'Cyber Arky 2099',
    descRo: 'Ochelari holografici neon și antenă laser albastră de mare viteză.',
    descEn: 'Neon holographic visor and blue high-speed laser antenna.',
    icon: '🕶️',
    price: 150,
    rarity: 'rare',
    previewAsset: 'cyber',
    badgeLabel: 'POPULAR',
  },
  {
    id: 'skin_scholar',
    category: 'arky_skin',
    nameRo: 'Arky Savant & Academician',
    nameEn: 'Scholar Arky',
    descRo: 'Tocă clasică de absolvent și ochelari de studiu pentru nota 10.',
    descEn: 'Graduation mortarboard and academic study glasses.',
    icon: '🎓',
    price: 200,
    rarity: 'rare',
    previewAsset: 'scholar',
  },
  {
    id: 'skin_astronaut',
    category: 'arky_skin',
    nameRo: 'Arky Cosmonaut Spațial',
    nameEn: 'Astronaut Arky',
    descRo: 'Cască spațială presurizată cu vizieră aurie pentru exploratori cosmici.',
    descEn: 'Pressurized space helmet with gold visor for cosmic explorers.',
    icon: '👨‍🚀',
    price: 350,
    rarity: 'epic',
    previewAsset: 'astronaut',
  },
  {
    id: 'skin_gamer',
    category: 'arky_skin',
    nameRo: 'Arky Pro Gamer RGB',
    nameEn: 'RGB Pro Gamer Arky',
    descRo: 'Căști mari de gaming cu lumini neon RGB și controller de duel.',
    descEn: 'Big RGB gaming headset and competitive duel controller.',
    icon: '🎧',
    price: 300,
    rarity: 'rare',
    previewAsset: 'gamer',
  },
  {
    id: 'skin_eco',
    category: 'arky_skin',
    nameRo: 'Arky Eco-Arhitect',
    nameEn: 'Eco-Architect Arky',
    descRo: 'Pelerină din frunze de stejar și crenguță ecologică (Inspirat din Modulul 4B).',
    descEn: 'Oak leaf cape and ecological branch (Module 4B inspired).',
    icon: '🌿',
    price: 250,
    rarity: 'rare',
    previewAsset: 'eco',
    requiredModule: 'text2',
  },
  {
    id: 'skin_wizard',
    category: 'arky_skin',
    nameRo: 'Arky Arhi-Magicianul Codului',
    nameEn: 'Code Arch-Mage Arky',
    descRo: 'Pălărie magică cu stele aurii și baghetă cu scântei binare 0 și 1.',
    descEn: 'Magical star hat and wand shooting binary 0 and 1 sparkles.',
    icon: '🧙‍♂️',
    price: 500,
    rarity: 'legendary',
    previewAsset: 'wizard',
    badgeLabel: 'LEGENDAR',
  },

  // ==================== 2. TEME DE INTERFAȚĂ (THEMES) ====================
  {
    id: 'theme_default',
    category: 'theme',
    nameRo: 'Cyber Slate (Implicit)',
    nameEn: 'Cyber Slate (Default)',
    descRo: 'Tema oficială modernă în nuanțe de ardezie întunecată și turcoaz.',
    descEn: 'Official modern dark slate and teal palette.',
    icon: '💻',
    price: 0,
    rarity: 'common',
    previewCss: 'from-slate-900 via-indigo-950 to-slate-900 border-teal-500/40',
  },
  {
    id: 'theme_matrix',
    category: 'theme',
    nameRo: 'Matrix Terminal Green',
    nameEn: 'Matrix Terminal Green',
    descRo: 'Fundal negru adânc cu linii de cod verde neon și accente de hacker etic.',
    descEn: 'Deep black background with matrix green cyber code accents.',
    icon: '🟢',
    price: 180,
    rarity: 'rare',
    previewCss: 'from-black via-emerald-950 to-black border-emerald-500 text-emerald-400',
  },
  {
    id: 'theme_synthwave',
    category: 'theme',
    nameRo: 'Cyberpunk Synthwave',
    nameEn: 'Cyberpunk Synthwave',
    descRo: 'Gradients retro-futuriste purpurii, roz neon și cyan electric.',
    descEn: 'Retro-futuristic neon purple, hot pink and electric cyan.',
    icon: '🌆',
    price: 260,
    rarity: 'epic',
    previewCss: 'from-purple-950 via-slate-950 to-pink-950 border-pink-500/60',
    badgeLabel: 'VIBRANT',
  },
  {
    id: 'theme_win98',
    category: 'theme',
    nameRo: 'Classic Retro OS 98',
    nameEn: 'Classic Retro OS 98',
    descRo: 'Stil vintage cu bare gri clasice, ferestre 3D bevel și font nostalgic.',
    descEn: 'Vintage 90s classic grey window chrome and 3D bevel styling.',
    icon: '💾',
    price: 220,
    rarity: 'rare',
    previewCss: 'from-slate-800 via-neutral-900 to-slate-800 border-neutral-400',
  },
  {
    id: 'theme_emerald',
    category: 'theme',
    nameRo: 'Emerald Eco-Forest',
    nameEn: 'Emerald Eco-Forest',
    descRo: 'Nuanțe naturale de verde smarald, mentă proaspătă și lemn cald.',
    descEn: 'Organic emerald forest greens, fresh mint and warm wood tones.',
    icon: '🌲',
    price: 200,
    rarity: 'rare',
    previewCss: 'from-emerald-950 via-teal-950 to-slate-950 border-emerald-400/50',
  },
  {
    id: 'theme_nebula',
    category: 'theme',
    nameRo: 'Deep Space Nebula',
    nameEn: 'Deep Space Nebula',
    descRo: 'Cosmos profund în nuanțe de albastru stelar, indigo și stele strălucitoare.',
    descEn: 'Deep cosmic starfields, celestial indigo and starlight glow.',
    icon: '🌌',
    price: 320,
    rarity: 'epic',
    previewCss: 'from-blue-950 via-indigo-950 to-violet-950 border-cyan-400/60',
  },
  {
    id: 'theme_sunset',
    category: 'theme',
    nameRo: 'Solar Sunset Gold',
    nameEn: 'Solar Sunset Gold',
    descRo: 'Auriu solar radiant, portocaliu cald și chihlimbar imperial.',
    descEn: 'Radiant solar gold, warm flame orange and imperial amber.',
    icon: '🌅',
    price: 400,
    rarity: 'legendary',
    previewCss: 'from-amber-950 via-orange-950 to-slate-950 border-amber-400/80',
    badgeLabel: 'PREMIUM',
  },

  // ==================== 3. RAME DE AVATAR (AVATAR FRAMES) ====================
  {
    id: 'frame_none',
    category: 'avatar_frame',
    nameRo: 'Fără Ramă',
    nameEn: 'Standard Border',
    descRo: 'Chenar standard curat.',
    descEn: 'Clean default avatar outline.',
    icon: '⚪',
    price: 0,
    rarity: 'common',
  },
  {
    id: 'frame_neon',
    category: 'avatar_frame',
    nameRo: 'Aura Neon Cyan',
    nameEn: 'Cyan Neon Pulse',
    descRo: 'Inel luminos pulsant în nuanțe de cyan electric.',
    descEn: 'Pulsing glowing ring in electric cyan.',
    icon: '💠',
    price: 120,
    rarity: 'rare',
    previewCss: 'ring-4 ring-cyan-400 shadow-lg shadow-cyan-500/40',
  },
  {
    id: 'frame_fire',
    category: 'avatar_frame',
    nameRo: 'Flăcări de Campion 🔥',
    nameEn: 'Champion Flames',
    descRo: 'Aură de flăcări portocalii pentru elevii cu streak-uri mari.',
    descEn: 'Fiery blaze aura for high-streak students.',
    icon: '🔥',
    price: 240,
    rarity: 'epic',
    previewCss: 'ring-4 ring-amber-500 shadow-xl shadow-orange-500/50',
  },
  {
    id: 'frame_gold',
    category: 'avatar_frame',
    nameRo: 'Contur Aur Masiv 24K',
    nameEn: '24K Solid Gold Crest',
    descRo: 'Ramă regală strălucitoare de aur pur.',
    descEn: 'Regal gleaming solid gold ornamental frame.',
    icon: '👑',
    price: 380,
    rarity: 'epic',
    previewCss: 'ring-4 ring-amber-300 shadow-xl shadow-amber-400/60 bg-gradient-to-tr from-amber-500 to-yellow-300',
  },
  {
    id: 'frame_diamond',
    category: 'avatar_frame',
    nameRo: 'Prismă de Diamant Cosmic',
    nameEn: 'Cosmic Diamond Prism',
    descRo: 'Ramă de diamant cu sclipiri multicolore de cristal pur.',
    descEn: 'Diamond frame sparkling with crystalline reflections.',
    icon: '💎',
    price: 550,
    rarity: 'legendary',
    previewCss: 'ring-4 ring-sky-300 shadow-2xl shadow-cyan-400/80',
    badgeLabel: 'ULTRA RAR',
  },
  {
    id: 'frame_emerald',
    category: 'avatar_frame',
    nameRo: 'Smarald Mistic',
    nameEn: 'Mystic Emerald Ring',
    descRo: 'Cerc radiant de smarald cu particule de natură.',
    descEn: 'Radiant emerald halo with nature particles.',
    icon: '✨',
    price: 180,
    rarity: 'rare',
    previewCss: 'ring-4 ring-emerald-400 shadow-lg shadow-emerald-500/40',
  },

  // ==================== 4. TITLURI ONORIFICE (TITLES) ====================
  {
    id: 'title_cadet',
    category: 'title',
    nameRo: 'Cadet TIC',
    nameEn: 'ICT Cadet',
    descRo: 'Titlul de debutant pentru orice explorator digital.',
    descEn: 'Beginner rank for every digital explorer.',
    icon: '🌱',
    price: 0,
    rarity: 'common',
  },
  {
    id: 'title_hw_engineer',
    category: 'title',
    nameRo: 'Inginer de Hardware',
    nameEn: 'Hardware Engineer',
    descRo: 'Expert în arhitectura PC, componente și ergonomie.',
    descEn: 'Master of PC architecture, hardware and ergonomics.',
    icon: '💻',
    price: 90,
    rarity: 'rare',
    requiredModule: 'hardware',
  },
  {
    id: 'title_file_master',
    category: 'title',
    nameRo: 'Stăpânul Arborelui de Fișiere',
    nameEn: 'File Tree Master',
    descRo: 'Specialist în structura folderelor și comenzi rapide.',
    descEn: 'Expert in directory hierarchies and shortcut mastery.',
    icon: '🌳',
    price: 100,
    rarity: 'rare',
    requiredModule: 'files',
  },
  {
    id: 'title_cyber_sheriff',
    category: 'title',
    nameRo: 'Sheriff Cyber-Safe',
    nameEn: 'Cyber-Safe Sheriff',
    descRo: 'Vânător neînfricat de viruși, phishing și capcane pe Internet.',
    descEn: 'Fearless hunter of malware, phishing traps and scams.',
    icon: '🛡️',
    price: 140,
    rarity: 'rare',
    requiredModule: 'internet2',
  },
  {
    id: 'title_doc_architect',
    category: 'title',
    nameRo: 'Arhitect de Documente & Ziare',
    nameEn: 'Document & Layout Architect',
    descRo: 'Maestru în tabele, proporții 1:1, text wrapping și format A4.',
    descEn: 'Master of tables, 1:1 ratios, text wrap and A4 layout.',
    icon: '📑',
    price: 160,
    rarity: 'epic',
    requiredModule: 'text2',
  },
  {
    id: 'title_algo_wizard',
    category: 'title',
    nameRo: 'Vrăjitorul Algoritmilor',
    nameEn: 'Algorithm Wizard',
    descRo: 'Gândire logică impecabilă și rezolvare de labirinturi.',
    descEn: 'Flawless logical reasoning and labyrinth solving.',
    icon: '⚡',
    price: 220,
    rarity: 'epic',
  },
  {
    id: 'title_tic_legend',
    category: 'title',
    nameRo: 'Legendă Absolută TIC',
    nameEn: 'Absolute ICT Legend',
    descRo: 'Cel mai înalt rang de distincție din școală.',
    descEn: 'The highest honorary distinction in the lab.',
    icon: '🏆',
    price: 600,
    rarity: 'legendary',
    badgeLabel: 'SUPREM',
  },
];

export const getCollectorRank = (ownedCount: number) => {
  if (ownedCount >= 18) {
    return { nameRo: 'Legendă TIC', nameEn: 'ICT Legend', icon: '👑', color: 'text-amber-300' };
  }
  if (ownedCount >= 12) {
    return { nameRo: 'Maestru Colecționar', nameEn: 'Master Collector', icon: '💎', color: 'text-cyan-300' };
  }
  if (ownedCount >= 6) {
    return { nameRo: 'Colecționar Avansat', nameEn: 'Advanced Collector', icon: '⭐', color: 'text-purple-300' };
  }
  return { nameRo: 'Ucenic Colecționar', nameEn: 'Novice Collector', icon: '🌱', color: 'text-emerald-300' };
};
