import React, { useState, useEffect, useRef } from 'react';
import { useLanguage } from '../../context/LanguageContext';
import { useArky } from '../../context/ArkyContext';
import { sounds } from '../../utils/audio';
import {
  Cpu,
  HardDrive,
  Monitor,
  Zap,
  RotateCcw,
  ArrowLeft,
  Trophy,
  CheckCircle2,
  AlertTriangle,
  Play,
  Sparkles,
  Info,
  Timer,
  Layers,
  ChevronRight,
  Power,
  Flame,
  Wrench,
  Fan,
  CircuitBoard,
  Lightbulb,
} from 'lucide-react';

interface PCBuilderGameProps {
  onBack: () => void;
  studentName?: string;
}

export type ComponentType =
  | 'cpu'
  | 'cooler'
  | 'ram1'
  | 'ram2'
  | 'gpu'
  | 'ssd'
  | 'psu';

export interface PCComponent {
  id: ComponentType;
  nameRo: string;
  nameEn: string;
  categoryRo: string;
  categoryEn: string;
  icon: string;
  color: string;
  borderColor: string;
  descriptionRo: string;
  descriptionEn: string;
  slotTarget: ComponentType;
  specsRo: string;
  specsEn: string;
}

export interface PCBuildLevel {
  id: number;
  nameRo: string;
  nameEn: string;
  subtitleRo: string;
  subtitleEn: string;
  targetDeviceRo: string;
  targetDeviceEn: string;
  timeLimit: number; // in seconds
  requiredComponents: ComponentType[];
  bonusNoteRo: string;
  bonusNoteEn: string;
}

const ALL_COMPONENTS: Record<ComponentType, PCComponent> = {
  cpu: {
    id: 'cpu',
    nameRo: 'Procesor (CPU Intel Core / AMD Ryzen)',
    nameEn: 'Processor (CPU)',
    categoryRo: 'Unitate Centrală de Prelucrare',
    categoryEn: 'Central Processing Unit',
    icon: '🔲',
    color: 'from-blue-600 to-indigo-700',
    borderColor: 'border-blue-400',
    descriptionRo: '„Creierul” calculatorului. Execută miliarde de calcule și instrucțiuni logice pe secundă.',
    descriptionEn: 'The "brain" of the computer. Executes billions of calculations and logic instructions per second.',
    slotTarget: 'cpu',
    specsRo: 'Socket LGA / AM5 • 8 Nuclee • 4.5 GHz',
    specsEn: 'Socket LGA / AM5 • 8 Cores • 4.5 GHz',
  },
  cooler: {
    id: 'cooler',
    nameRo: 'Sistem Răcire CPU (Cooler & Ventilator)',
    nameEn: 'CPU Cooler & Fan',
    categoryRo: 'Disipare Termică',
    categoryEn: 'Thermal Dissipation',
    icon: '❄️',
    color: 'from-cyan-600 to-blue-600',
    borderColor: 'border-cyan-400',
    descriptionRo: 'Disipă căldura intensă generată de procesor prin pastă termică, lamele de cupru și ventilator.',
    descriptionEn: 'Dissipates intense heat generated by CPU through thermal paste, copper fins, and active fan.',
    slotTarget: 'cooler',
    specsRo: 'Radiator Cupru • 2000 RPM • Silențios',
    specsEn: 'Copper Heatsink • 2000 RPM • Silent',
  },
  ram1: {
    id: 'ram1',
    nameRo: 'Modul RAM DDR5 (Slot A2)',
    nameEn: 'DDR5 RAM Stick (Slot A2)',
    categoryRo: 'Memorie Rapidă cu Acces Aleator',
    categoryEn: 'Random Access Memory',
    icon: '⚡',
    color: 'from-amber-600 to-yellow-600',
    borderColor: 'border-amber-400',
    descriptionRo: 'Memorie de lucru ultra-rapidă, dar volatilă (se șterge la oprirea curentului). Ține programele deschise.',
    descriptionEn: 'Ultra-fast working memory, volatile (wiped on power loss). Holds actively running applications.',
    slotTarget: 'ram1',
    specsRo: '16 GB DDR5 • 6000 MHz • CL30',
    specsEn: '16 GB DDR5 • 6000 MHz • CL30',
  },
  ram2: {
    id: 'ram2',
    nameRo: 'Modul RAM DDR5 (Slot B2 - Dual Channel)',
    nameEn: 'DDR5 RAM Stick (Slot B2 - Dual Channel)',
    categoryRo: 'Memorie RAM Extensie',
    categoryEn: 'RAM Extension Stick',
    icon: '⚡',
    color: 'from-amber-600 to-yellow-600',
    borderColor: 'border-amber-400',
    descriptionRo: 'Al doilea modul activează modul „Dual Channel”, dublând lățimea de bandă a memoriei pentru procesor!',
    descriptionEn: 'Second stick unlocks "Dual Channel" mode, doubling memory bandwidth for CPU throughput!',
    slotTarget: 'ram2',
    specsRo: '16 GB DDR5 • Dual-Channel Enabled',
    specsEn: '16 GB DDR5 • Dual-Channel Enabled',
  },
  gpu: {
    id: 'gpu',
    nameRo: 'Placă Video Dedicată (GPU RTX / Radeon)',
    nameEn: 'Dedicated Graphics Card (GPU)',
    categoryRo: 'Procesare Grafică & 3D',
    categoryEn: 'Graphics & 3D Processor',
    icon: '🎮',
    color: 'from-emerald-600 to-teal-700',
    borderColor: 'border-emerald-400',
    descriptionRo: 'Procesează miliardele de pixeli pentru jocuri 3D, randare video, modelare și inteligență artificială.',
    descriptionEn: 'Renders billions of pixels for 3D games, video streaming, modeling, and AI model acceleration.',
    slotTarget: 'gpu',
    specsRo: 'Slot PCIe 4.0 x16 • 12 GB VRAM • Ray Tracing',
    specsEn: 'PCIe 4.0 x16 Slot • 12 GB VRAM • Ray Tracing',
  },
  ssd: {
    id: 'ssd',
    nameRo: 'Stocare SSD M.2 NVMe (Solid State Drive)',
    nameEn: 'M.2 NVMe SSD Storage',
    categoryRo: 'Memorie Externă Non-Volatilă',
    categoryEn: 'Non-Volatile Storage',
    icon: '💾',
    color: 'from-purple-600 to-violet-700',
    borderColor: 'border-purple-400',
    descriptionRo: 'Păstrează sistemul de operare și fișierele permanent (nu se pierd la oprirea PC-ului). Viteze de până la 7000 MB/s.',
    descriptionEn: 'Stores OS and files permanently without power. Ultra-fast data transfer up to 7000 MB/s.',
    slotTarget: 'ssd',
    specsRo: '1 TB NVMe Gen4 • 7450 MB/s Citire',
    specsEn: '1 TB NVMe Gen4 • 7450 MB/s Read',
  },
  psu: {
    id: 'psu',
    nameRo: 'Sursă de Alimentare (PSU 750W Gold)',
    nameEn: 'Power Supply Unit (PSU 750W)',
    categoryRo: 'Alimentare & Conversie Tensiune',
    categoryEn: 'Power Conversion & Delivery',
    icon: '🔌',
    color: 'from-rose-600 to-red-700',
    borderColor: 'border-rose-400',
    descriptionRo: 'Transformă curentul alternativ de la priză (230V) în curent continuu stabil (12V, 5V, 3.3V) pentru toate componentele.',
    descriptionEn: 'Converts high AC wall power (230V) into regulated DC power (12V, 5V, 3.3V) for PC components.',
    slotTarget: 'psu',
    specsRo: '750W • 80+ Gold Modular • Protecție Supratensiune',
    specsEn: '750W • 80+ Gold Modular • Surge Protected',
  },
};

const PC_BUILD_LEVELS: PCBuildLevel[] = [
  {
    id: 1,
    nameRo: 'Nivelul 1: PC de Birou & Școală (Office Starter)',
    nameEn: 'Level 1: School & Office PC (Office Starter)',
    subtitleRo: 'Asamblează arhitectura minimă funcțională a unui calculator',
    subtitleEn: 'Assemble the minimum viable computer architecture',
    targetDeviceRo: 'Desktop TIC de Sală de Clasă',
    targetDeviceEn: 'Classroom Desktop PC',
    timeLimit: 50,
    requiredComponents: ['cpu', 'cooler', 'ram1', 'ssd', 'psu'],
    bonusNoteRo: 'Sfat didactic: Oricărui PC îi sunt esențiale CPU, RAM, Stocare și Sursă pentru a putea boota.',
    bonusNoteEn: 'Pro tip: Any PC fundamentally requires CPU, RAM, Storage, and PSU to POST boot.',
  },
  {
    id: 2,
    nameRo: 'Nivelul 2: PC de Gaming & Editare Video (Power Rig)',
    nameEn: 'Level 2: Gaming & Content Creator Rig (Power Rig)',
    subtitleRo: 'Adaugă memorie RAM Dual-Channel și o placă video dedicată',
    subtitleEn: 'Add Dual-Channel RAM and a dedicated graphics processor',
    targetDeviceRo: 'Stație de Gaming & Grafică 3D',
    targetDeviceEn: 'Gaming & 3D Graphics Rig',
    timeLimit: 60,
    requiredComponents: ['cpu', 'cooler', 'ram1', 'ram2', 'gpu', 'ssd', 'psu'],
    bonusNoteRo: 'Sfat didactic: Folosirea ambelor sloturi RAM activează lățimea dublă de bandă pentru GPU și CPU!',
    bonusNoteEn: 'Pro tip: Populating both RAM channels doubles the memory bandwidth for GPU and CPU!',
  },
  {
    id: 3,
    nameRo: 'Nivelul 3: Supercomputer de Laborator AI & Server',
    nameEn: 'Level 3: AI Lab Workstation & Cloud Server',
    subtitleRo: 'Asamblare de mare precizie contra cronometru în laborator',
    subtitleEn: 'High-speed assembly under strict laboratory pressure',
    targetDeviceRo: 'Server Didactic de Rețea Arkedo',
    targetDeviceEn: 'Arkedo Network Education Server',
    timeLimit: 40,
    requiredComponents: ['cpu', 'cooler', 'ram1', 'ram2', 'gpu', 'ssd', 'psu'],
    bonusNoteRo: 'Provocare viteză: Montează toate cele 7 piese înainte de expirarea celor 40 de secunde!',
    bonusNoteEn: 'Speed challenge: Mount all 7 components before the 40s timer runs out!',
  },
];

export const PCBuilderGame: React.FC<PCBuilderGameProps> = ({ onBack, studentName }) => {
  const { lang } = useLanguage();
  const arky = useArky();

  const [currentLevelIdx, setCurrentLevelIdx] = useState<number>(0);
  const currentLevel = PC_BUILD_LEVELS[currentLevelIdx];

  // Game state
  const [placedSlots, setPlacedSlots] = useState<Partial<Record<ComponentType, boolean>>>({});
  const [selectedConveyorItem, setSelectedConveyorItem] = useState<ComponentType | null>(null);
  const [showHint, setShowHint] = useState<boolean>(false);
  const [timeLeft, setTimeLeft] = useState<number>(currentLevel.timeLimit);
  const [isTimerRunning, setIsTimerRunning] = useState<boolean>(false);
  const [score, setScore] = useState<number>(0);
  const [shortCircuitSlot, setShortCircuitSlot] = useState<ComponentType | null>(null);
  const [shortCircuitMsg, setShortCircuitMsg] = useState<string | null>(null);
  const [isBooting, setIsBooting] = useState<boolean>(false);
  const [bootLog, setBootLog] = useState<string[]>([]);
  const [isBootSuccess, setIsBootSuccess] = useState<boolean>(false);
  const [isGameOverTimeout, setIsGameOverTimeout] = useState<boolean>(false);
  const [isCompletedAll, setIsCompletedAll] = useState<boolean>(false);
  const [hoveredComponent, setHoveredComponent] = useState<PCComponent | null>(null);

  // High score
  const [highScore, setHighScore] = useState<number>(() => {
    try {
      return Number(localStorage.getItem('arkedo_highscore_pcbuilder') || '0');
    } catch {
      return 0;
    }
  });

  // Remaining components on conveyor belt
  const conveyorItems = currentLevel.requiredComponents.filter((id) => !placedSlots[id]);
  const isAllPlaced = conveyorItems.length === 0;

  // Initialize level
  const initLevel = () => {
    setPlacedSlots({});
    setSelectedConveyorItem(null);
    setShowHint(false);
    setTimeLeft(currentLevel.timeLimit);
    setIsTimerRunning(true);
    setShortCircuitSlot(null);
    setShortCircuitMsg(null);
    setIsBooting(false);
    setBootLog([]);
    setIsBootSuccess(false);
    setIsGameOverTimeout(false);
    setHoveredComponent(null);
  };

  const handleToggleHint = () => {
    sounds.playClick();
    if (showHint) {
      setShowHint(false);
      return;
    }

    // If no piece is currently selected, pick the first unplaced piece on the conveyor belt
    let targetCompKey = selectedConveyorItem;
    if (!targetCompKey && conveyorItems.length > 0) {
      targetCompKey = conveyorItems[0];
      setSelectedConveyorItem(targetCompKey);
      setHoveredComponent(ALL_COMPONENTS[targetCompKey]);
    }

    if (targetCompKey) {
      setShowHint(true);
      const comp = ALL_COMPONENTS[targetCompKey];
      arky.triggerIdle(
        lang === 'en'
          ? `💡 Hint: ${comp.nameEn} fits into the glowing amber slot on the motherboard!`
          : `💡 Indiciu: ${comp.nameRo} trebuie montat în slotul evidențiat cu galben pe placa de bază!`
      );
    }
  };

  useEffect(() => {
    initLevel();
  }, [currentLevelIdx]);

  // Timer countdown
  useEffect(() => {
    if (!isTimerRunning || isBootSuccess || isGameOverTimeout) return;

    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          handleTimeout();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [isTimerRunning, isBootSuccess, isGameOverTimeout]);

  const handleTimeout = () => {
    setIsTimerRunning(false);
    setIsGameOverTimeout(true);
    sounds.playWrong();
    arky.triggerIdle();
  };

  // Attempt to place a component into a slot
  const handleSlotAttempt = (targetSlot: ComponentType) => {
    if (isGameOverTimeout || isBootSuccess || isBooting) return;

    if (!selectedConveyorItem) {
      // Nothing selected
      return;
    }

    const component = ALL_COMPONENTS[selectedConveyorItem];

    // Already occupied?
    if (placedSlots[targetSlot]) {
      sounds.playWrong();
      return;
    }

    // Correct placement check
    if (selectedConveyorItem === targetSlot) {
      // SUCCESS! Component fits
      sounds.playCorrect();
      setPlacedSlots((prev) => ({ ...prev, [targetSlot]: true }));
      setSelectedConveyorItem(null);
      setShowHint(false);
      setShortCircuitSlot(null);
      setShortCircuitMsg(null);

      // Score bonus
      const points = 100 + timeLeft * 5;
      setScore((prev) => prev + points);

      arky.triggerSuccess(
        lang === 'en'
          ? `Great! ${component.nameEn} mounted properly into its motherboard slot!`
          : `Excelent! ${component.nameRo} montat corect în slotul său!`
      );
    } else {
      // MISMATCH! Short circuit comic bounce
      sounds.playWrong();
      setShortCircuitSlot(targetSlot);

      const targetDesc = ALL_COMPONENTS[targetSlot].nameRo;
      const wrongMsg =
        lang === 'en'
          ? `⚡ SHORT CIRCUIT! Cannot install ${component.nameEn} into ${targetDesc} slot! Component bounced back!`
          : `⚡ SCURTCIRCUIT! Nu poți monta ${component.nameRo} în slotul destinat pentru ${targetDesc}! Piesa a sărit înapoi!`;

      setShortCircuitMsg(wrongMsg);

      // Auto clear short circuit animation after 1.8s
      setTimeout(() => {
        setShortCircuitSlot(null);
        setShortCircuitMsg(null);
      }, 1800);
    }
  };

  // Run POST boot sequence
  const startBootSequence = async () => {
    if (!isAllPlaced || isBooting) return;

    sounds.playClick();
    setIsBooting(true);
    setIsTimerRunning(false);
    setBootLog([]);

    const steps = [
      '⚡ [POWER ON] Sursa de 750W trimite tensiune stabilă de 12V pe placa de bază...',
      '🔍 [POST] Verificare integritate CPU: 8 Nuclee active, frecvență nominală OK.',
      '❄️ [COOLER] Ventilatoarele pornesc la 1800 RPM. Temperatură procesor: 32°C.',
      '⚡ [RAM] Detectat DDR5 în Dual-Channel: 32 GB activi la 6000 MHz.',
      '🎮 [GPU] Placa grafică PCIe 4.0 x16 inițializată. Semnal video HDMI/DP OK.',
      '💾 [SSD] Încărcare M.2 NVMe SSD: Partitie sistem ArkedoOS detectată.',
      '🚀 [BOOT SUCCESS] Calculator asamblat perfect! ArkedoOS pornește în 2.3 secunde!',
    ];

    for (let i = 0; i < steps.length; i++) {
      await new Promise((resolve) => setTimeout(resolve, 550));
      setBootLog((prev) => [...prev, steps[i]]);
      sounds.playClick();
    }

    sounds.playVictory();
    setIsBootSuccess(true);
    setIsBooting(false);

    const bonusCompletion = 300 + timeLeft * 10;
    const finalScore = score + bonusCompletion;
    setScore(finalScore);

    if (finalScore > highScore) {
      setHighScore(finalScore);
      try {
        localStorage.setItem('arkedo_highscore_pcbuilder', String(finalScore));
      } catch {
        // ignore
      }
    }

    if (currentLevelIdx + 1 >= PC_BUILD_LEVELS.length) {
      setIsCompletedAll(true);
      arky.triggerFinished(
        lang === 'en'
          ? `Hardware Master Engineer! You assembled and booted all computer configurations with zero casualties!`
          : `Inginer Hardware Maestru! Ai asamblat și pornit toate calculatoarele fără nicio greșeală de montare! 🖥️⚡`
      );
    } else {
      arky.triggerSuccess(
        lang === 'en'
          ? `PC Boot Successful! System is operating at peak performance!`
          : `PC-ul a bootat cu succes! Sistemul funcționează la performanță maximă! 🚀💻`
      );
    }
  };

  const handleNextLevel = () => {
    sounds.playClick();
    if (currentLevelIdx + 1 < PC_BUILD_LEVELS.length) {
      setCurrentLevelIdx((prev) => prev + 1);
    }
  };

  const handleRestartWholeGame = () => {
    sounds.playClick();
    setCurrentLevelIdx(0);
    setScore(0);
    setIsCompletedAll(false);
    initLevel();
    arky.triggerIdle();
  };

  return (
    <div className="flex flex-col gap-5 max-w-6xl mx-auto w-full pb-10 select-none">
      {/* Top Header Bar */}
      <div className="flex flex-wrap sm:flex-nowrap items-center justify-between gap-3 bg-slate-900/90 border border-slate-700/80 rounded-2xl p-3 sm:p-4 shadow-xl">
        <button
          onClick={() => {
            sounds.playClick();
            onBack();
          }}
          className="order-1 px-3 py-2 rounded-xl bg-slate-800 hover:bg-slate-750 text-slate-200 hover:text-white border border-slate-700 text-xs sm:text-sm font-bold transition flex items-center gap-1.5 cursor-pointer active:scale-95 shrink-0"
        >
          <ArrowLeft className="w-4 h-4 text-emerald-400" />
          <span>{lang === 'en' ? 'Arcade' : 'Înapoi'}</span>
        </button>

        <div className="order-3 sm:order-2 w-full sm:w-auto flex items-center gap-2.5 text-left sm:text-center justify-start sm:justify-center">
          <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-2xl bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center text-white shadow-md shadow-blue-500/20 shrink-0">
            <Cpu className="w-5 h-5" />
          </div>
          <div>
            <h1 className="text-xs sm:text-base font-black text-white font-heading">
              {lang === 'en' ? 'PC Builder: Hardware Mission' : 'Constructorul de PC-uri'}
            </h1>
            <p className="text-[10px] sm:text-[11px] text-blue-400 font-mono">
              {lang === 'en' ? 'Mount CPU, RAM, GPU & SSD onto Motherboard' : 'Montează CPU, RAM, GPU și SSD pe Placa de Bază'}
            </p>
          </div>
        </div>

        {/* High Score Badge */}
        <div className="order-2 sm:order-3 flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5 rounded-xl bg-blue-500/10 border border-blue-500/30 text-blue-300 text-xs font-mono font-bold shrink-0">
          <Trophy className="w-4 h-4 text-amber-400 shrink-0" />
          <span>{highScore} pts</span>
        </div>
      </div>

      {!isCompletedAll ? (
        <div className="bg-slate-900/95 border-2 border-blue-500/30 rounded-3xl p-5 sm:p-6 shadow-2xl flex flex-col gap-5 relative">
          {/* Subheader: Level info, Countdown, Score, Restart Level */}
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
            <div className="flex flex-wrap items-center gap-2.5">
              <span className="px-3 py-1.5 rounded-xl bg-blue-500/15 border border-blue-500/30 text-xs font-mono font-bold text-blue-300">
                {lang === 'en' ? `Level ${currentLevel.id} / ${PC_BUILD_LEVELS.length}` : `Nivelul ${currentLevel.id} / ${PC_BUILD_LEVELS.length}`}
              </span>
              <div>
                <h2 className="text-sm sm:text-base font-bold text-white">
                  {lang === 'en' ? currentLevel.nameEn : currentLevel.nameRo}
                </h2>
                <div className="text-[11px] text-blue-400/80 font-mono">
                  🎯 Țintă: {lang === 'en' ? currentLevel.targetDeviceEn : currentLevel.targetDeviceRo}
                </div>
              </div>
            </div>

            <div className="flex items-center gap-3">
              {/* Timer */}
              <div
                className={`px-3.5 py-1.5 rounded-xl border flex items-center gap-2 font-mono text-sm font-bold transition-all ${
                  timeLeft <= 10
                    ? 'bg-rose-500/20 text-rose-300 border-rose-500/50 animate-pulse'
                    : 'bg-slate-950 text-blue-300 border-slate-800'
                }`}
              >
                <Timer className="w-4 h-4 text-amber-400" />
                <span>{timeLeft}s</span>
              </div>

              {/* Score */}
              <div className="bg-slate-950 px-3.5 py-1.5 rounded-xl border border-slate-800 flex items-center gap-1.5">
                <Trophy className="w-4 h-4 text-emerald-400" />
                <span className="text-sm font-black text-white font-mono">{score} pts</span>
              </div>

              {/* Hint Button */}
              <button
                type="button"
                onClick={handleToggleHint}
                title={lang === 'en' ? 'Show where to install component' : 'Arată unde se montează piesa (Indiciu)'}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold font-mono transition flex items-center gap-1.5 cursor-pointer border active:scale-95 ${
                  showHint
                    ? 'bg-amber-500 text-slate-950 border-amber-400 shadow-lg shadow-amber-500/30 animate-pulse'
                    : 'bg-slate-800 hover:bg-slate-750 text-amber-300 border-amber-500/40 hover:border-amber-400'
                }`}
              >
                <Lightbulb className={`w-4 h-4 ${showHint ? 'text-slate-950' : 'text-amber-400'}`} />
                <span>{showHint ? (lang === 'en' ? 'Hint Active' : 'Indiciu Activ') : (lang === 'en' ? 'Hint' : 'Indiciu')}</span>
              </button>

              {/* Reset Level Button */}
              <button
                onClick={initLevel}
                title={lang === 'en' ? 'Restart Current Level' : 'Reia Nivelul Curent'}
                className="p-2 rounded-xl bg-slate-800 hover:bg-slate-750 text-slate-300 hover:text-white border border-slate-700 transition cursor-pointer"
              >
                <RotateCcw className="w-4 h-4 text-cyan-400" />
              </button>
            </div>
          </div>

          {/* Short Circuit Warning Alert */}
          {shortCircuitMsg && (
            <div className="p-3.5 rounded-2xl bg-rose-500/20 border-2 border-rose-500/60 text-rose-200 text-xs font-bold font-mono animate-bounce flex items-center gap-3 shadow-lg shadow-rose-500/20">
              <Zap className="w-5 h-5 text-amber-400 shrink-0 animate-pulse" />
              <div className="flex-1">{shortCircuitMsg}</div>
            </div>
          )}

          {/* Main Workshop Grid: Motherboard Stage & Component Conveyor Belt */}
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
            {/* Mobile Fast Component Selector Strip (Visible on mobile/tablet < lg) */}
            <div className="lg:hidden col-span-1 flex flex-col gap-2 p-3 rounded-2xl bg-slate-950 border border-slate-800">
              <div className="flex items-center justify-between text-xs font-mono font-bold text-slate-300">
                <span className="flex items-center gap-1.5">
                  <Wrench className="w-3.5 h-3.5 text-blue-400" />
                  {lang === 'en' ? 'Parts to Install:' : 'Piese de montat:'} ({conveyorItems.length})
                </span>
                {selectedConveyorItem && (
                  <span className="text-[10px] text-amber-400 font-bold animate-pulse">
                    {ALL_COMPONENTS[selectedConveyorItem].nameRo} ➔ {lang === 'en' ? 'Tap slot!' : 'Atinge slotul!'}
                  </span>
                )}
              </div>
              <div className="flex gap-2 overflow-x-auto pb-1.5 pt-0.5 no-scrollbar">
                {conveyorItems.map((slotKey) => {
                  const info = ALL_COMPONENTS[slotKey];
                  const isSelected = selectedConveyorItem === slotKey;
                  return (
                    <button
                      key={slotKey}
                      type="button"
                      onClick={() => {
                        sounds.playClick();
                        setSelectedConveyorItem(slotKey);
                        setHoveredComponent(info);
                      }}
                      className={`shrink-0 px-3 py-2 rounded-xl border flex items-center gap-2 transition-all cursor-pointer active:scale-95 ${
                        isSelected
                          ? 'bg-blue-600/30 border-blue-400 text-white ring-2 ring-blue-400/50 shadow-lg shadow-blue-500/20'
                          : 'bg-slate-900 border-slate-700 text-slate-300 hover:bg-slate-800'
                      }`}
                    >
                      <span className="text-lg">{info.icon}</span>
                      <div className="text-left">
                        <div className="text-xs font-bold leading-tight">{info.nameRo}</div>
                        <div className="text-[9px] text-slate-400 font-mono">{info.categoryRo}</div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Left/Center: The Motherboard (PCB Stage) */}
            <div className="lg:col-span-8 flex flex-col bg-slate-950/95 border-2 border-slate-800 rounded-3xl p-3 sm:p-5 shadow-2xl relative overflow-hidden">
              {/* Motherboard Header & Status */}
              <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-800 pb-3 mb-4">
                <div className="flex items-center gap-2">
                  <CircuitBoard className="w-5 h-5 text-blue-400 shrink-0" />
                  <span className="text-xs font-black text-white font-mono tracking-wider uppercase">
                    Placă de Bază ATX • Arkedo-Z790
                  </span>
                </div>
                <span className="text-[11px] font-mono text-emerald-400 font-bold bg-emerald-500/10 px-2.5 py-0.5 rounded-md border border-emerald-500/30">
                  Montate: {Object.keys(placedSlots).length} / {currentLevel.requiredComponents.length} piese
                </span>
              </div>

              {/* Visual Motherboard Layout */}
              <div className="overflow-x-auto pb-1 -mx-1 px-1 sm:mx-0 sm:px-0">
                <div className="relative w-full min-w-[310px] min-h-[440px] sm:min-h-0 sm:aspect-[4/3] max-w-[620px] mx-auto bg-emerald-950/20 border-2 border-emerald-500/30 rounded-2xl p-3 sm:p-4 flex flex-col justify-between shadow-inner">
                  {/* Motherboard Trace Lines Background Decoration */}
                  <div className="absolute inset-0 opacity-10 pointer-events-none bg-[radial-gradient(#10b981_1px,transparent_1px)] [background-size:16px_16px]"></div>

                {/* Top Section: CPU Socket & Cooler Mount + RAM Slots */}
                <div className="flex items-start justify-between gap-3 relative z-10">
                  {/* CPU + Cooler Stack Area */}
                  <div className="flex flex-col gap-2">
                    {/* CPU Socket */}
                    <button
                      type="button"
                      onClick={() => handleSlotAttempt('cpu')}
                      className={`w-32 sm:w-36 h-28 rounded-2xl border-2 flex flex-col items-center justify-center p-2 transition-all duration-300 cursor-pointer relative ${
                        placedSlots.cpu
                          ? 'bg-blue-950/80 border-blue-400 shadow-md shadow-blue-500/20'
                          : shortCircuitSlot === 'cpu'
                          ? 'bg-rose-900/60 border-rose-500 scale-105 animate-wiggle'
                          : showHint && selectedConveyorItem === 'cpu'
                          ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                          : selectedConveyorItem
                          ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                          : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                      }`}
                    >
                      {showHint && selectedConveyorItem === 'cpu' && (
                        <span className="absolute -top-2.5 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[9px] font-black uppercase tracking-wider animate-bounce shadow-md">
                          💡 Aici!
                        </span>
                      )}
                      <span className="text-xl sm:text-2xl">
                        {placedSlots.cpu ? '🔲' : '⬛'}
                      </span>
                      <span className="text-[11px] font-bold text-white mt-1">
                        Socket CPU (LGA)
                      </span>
                      <span className="text-[9px] font-mono text-slate-400">
                        {placedSlots.cpu ? '✅ CPU Instalat' : 'Slot Procesor'}
                      </span>
                    </button>

                    {/* CPU Cooler Slot (mounted over CPU) */}
                    {currentLevel.requiredComponents.includes('cooler') && (
                      <button
                        type="button"
                        onClick={() => handleSlotAttempt('cooler')}
                        className={`w-32 sm:w-36 h-20 rounded-2xl border-2 flex flex-col items-center justify-center p-1.5 transition-all duration-300 cursor-pointer relative ${
                          placedSlots.cooler
                            ? 'bg-cyan-950/80 border-cyan-400 shadow-md shadow-cyan-500/20'
                            : shortCircuitSlot === 'cooler'
                            ? 'bg-rose-900/60 border-rose-500 scale-105 animate-wiggle'
                            : showHint && selectedConveyorItem === 'cooler'
                            ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                            : selectedConveyorItem
                            ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                            : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                        }`}
                      >
                        {showHint && selectedConveyorItem === 'cooler' && (
                          <span className="absolute -top-2 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[9px] font-black uppercase tracking-wider animate-bounce shadow-md">
                            💡 Aici!
                          </span>
                        )}
                        <Fan
                          className={`w-5 h-5 ${
                            placedSlots.cooler ? 'text-cyan-300 animate-spin' : 'text-slate-500'
                          }`}
                        />
                        <span className="text-[10px] font-bold text-white mt-0.5">
                          Cooler & Ventilator
                        </span>
                        <span className="text-[9px] font-mono text-slate-400">
                          {placedSlots.cooler ? '✅ Răcire Activă' : 'Fixare pe procesor'}
                        </span>
                      </button>
                    )}
                  </div>

                  {/* Dual RAM DIMM Slots */}
                  <div className="flex gap-2">
                    {/* RAM Slot 1 */}
                    <button
                      type="button"
                      onClick={() => handleSlotAttempt('ram1')}
                      className={`w-14 sm:w-16 h-52 rounded-2xl border-2 flex flex-col items-center justify-between p-2 transition-all duration-300 cursor-pointer relative ${
                        placedSlots.ram1
                          ? 'bg-amber-950/80 border-amber-400 shadow-md shadow-amber-500/20'
                          : shortCircuitSlot === 'ram1'
                          ? 'bg-rose-900/60 border-rose-500 scale-105 animate-wiggle'
                          : showHint && selectedConveyorItem === 'ram1'
                          ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                          : selectedConveyorItem
                          ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                          : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                      }`}
                    >
                      {showHint && selectedConveyorItem === 'ram1' && (
                        <span className="absolute -top-2.5 px-1.5 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[8px] font-black uppercase tracking-wider animate-bounce shadow-md">
                          💡 Aici!
                        </span>
                      )}
                      <span className="text-[9px] font-mono font-bold text-amber-300">DIMM A2</span>
                      <div className="flex flex-col items-center justify-center gap-1">
                        <span className="text-lg">{placedSlots.ram1 ? '⚡' : '▫️'}</span>
                        <span className="text-[9px] font-bold text-white text-center leading-tight">
                          {placedSlots.ram1 ? '16 GB DDR5' : 'Slot RAM 1'}
                        </span>
                      </div>
                      <span className="text-[8px] font-mono text-slate-400">
                        {placedSlots.ram1 ? 'Activ' : 'Liber'}
                      </span>
                    </button>

                    {/* RAM Slot 2 (Level 2 & 3) */}
                    {currentLevel.requiredComponents.includes('ram2') && (
                      <button
                        type="button"
                        onClick={() => handleSlotAttempt('ram2')}
                        className={`w-14 sm:w-16 h-52 rounded-2xl border-2 flex flex-col items-center justify-between p-2 transition-all duration-300 cursor-pointer relative ${
                          placedSlots.ram2
                            ? 'bg-amber-950/80 border-amber-400 shadow-md shadow-amber-500/20'
                            : shortCircuitSlot === 'ram2'
                            ? 'bg-rose-900/60 border-rose-500 scale-105 animate-wiggle'
                            : showHint && selectedConveyorItem === 'ram2'
                            ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                            : selectedConveyorItem
                            ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                            : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                        }`}
                      >
                        {showHint && selectedConveyorItem === 'ram2' && (
                          <span className="absolute -top-2.5 px-1.5 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[8px] font-black uppercase tracking-wider animate-bounce shadow-md">
                            💡 Aici!
                          </span>
                        )}
                        <span className="text-[9px] font-mono font-bold text-amber-300">DIMM B2</span>
                        <div className="flex flex-col items-center justify-center gap-1">
                          <span className="text-lg">{placedSlots.ram2 ? '⚡' : '▫️'}</span>
                          <span className="text-[9px] font-bold text-white text-center leading-tight">
                            {placedSlots.ram2 ? 'Dual-Ch' : 'Slot RAM 2'}
                          </span>
                        </div>
                        <span className="text-[8px] font-mono text-slate-400">
                          {placedSlots.ram2 ? 'Dual-Ch' : 'Liber'}
                        </span>
                      </button>
                    )}
                  </div>
                </div>

                {/* Middle & Bottom Section: GPU PCIe Slot, SSD M.2, PSU */}
                <div className="flex flex-col gap-2.5 relative z-10 mt-2">
                  {/* GPU Slot (PCIe x16) */}
                  {currentLevel.requiredComponents.includes('gpu') && (
                    <button
                      type="button"
                      onClick={() => handleSlotAttempt('gpu')}
                      className={`w-full h-16 rounded-2xl border-2 flex items-center justify-between px-4 transition-all duration-300 cursor-pointer relative ${
                        placedSlots.gpu
                          ? 'bg-emerald-950/80 border-emerald-400 shadow-md shadow-emerald-500/20'
                          : shortCircuitSlot === 'gpu'
                          ? 'bg-rose-900/60 border-rose-500 scale-102 animate-wiggle'
                          : showHint && selectedConveyorItem === 'gpu'
                          ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                          : selectedConveyorItem
                          ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                          : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                      }`}
                    >
                      {showHint && selectedConveyorItem === 'gpu' && (
                        <span className="absolute -top-2.5 right-4 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[9px] font-black uppercase tracking-wider animate-bounce shadow-md">
                          💡 Aici se montează!
                        </span>
                      )}
                      <div className="flex items-center gap-2.5">
                        <span className="text-xl">{placedSlots.gpu ? '🎮' : '➖'}</span>
                        <div className="text-left">
                          <div className="text-xs font-bold text-white">Slot PCIe 4.0 x16 (Placă Video GPU)</div>
                          <div className="text-[10px] font-mono text-emerald-400">
                            {placedSlots.gpu ? '✅ Placă Grafică Dedicată Fixată' : 'Slot lățime de bandă maximă'}
                          </div>
                        </div>
                      </div>
                      <span className="text-[10px] font-mono font-bold text-slate-400">
                        {placedSlots.gpu ? 'PCIe x16 OK' : 'Slot Liber'}
                      </span>
                    </button>
                  )}

                  {/* Bottom Row: SSD M.2 Slot & Power Supply (PSU) */}
                  <div className="flex items-center justify-between gap-3">
                    {/* SSD M.2 NVMe Slot */}
                    <button
                      type="button"
                      onClick={() => handleSlotAttempt('ssd')}
                      className={`flex-1 h-16 rounded-2xl border-2 flex items-center justify-between px-3 transition-all duration-300 cursor-pointer relative ${
                        placedSlots.ssd
                          ? 'bg-purple-950/80 border-purple-400 shadow-md shadow-purple-500/20'
                          : shortCircuitSlot === 'ssd'
                          ? 'bg-rose-900/60 border-rose-500 scale-102 animate-wiggle'
                          : showHint && selectedConveyorItem === 'ssd'
                          ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                          : selectedConveyorItem
                          ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                          : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                      }`}
                    >
                      {showHint && selectedConveyorItem === 'ssd' && (
                        <span className="absolute -top-2.5 right-3 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[9px] font-black uppercase tracking-wider animate-bounce shadow-md">
                          💡 Aici!
                        </span>
                      )}
                      <div className="flex items-center gap-2">
                        <span className="text-lg">{placedSlots.ssd ? '💾' : '▫️'}</span>
                        <div className="text-left">
                          <div className="text-[11px] font-bold text-white">Slot M.2 NVMe</div>
                          <div className="text-[9px] font-mono text-purple-300">
                            {placedSlots.ssd ? '✅ SSD 1 TB Montat' : 'Stocare Rapidă'}
                          </div>
                        </div>
                      </div>
                      <span className="text-[8px] font-mono text-slate-400">M.2 Gen4</span>
                    </button>

                    {/* PSU Bay (Sursa de Alimentare) */}
                    <button
                      type="button"
                      onClick={() => handleSlotAttempt('psu')}
                      className={`flex-1 h-16 rounded-2xl border-2 flex items-center justify-between px-3 transition-all duration-300 cursor-pointer relative ${
                        placedSlots.psu
                          ? 'bg-rose-950/80 border-rose-400 shadow-md shadow-rose-500/20'
                          : shortCircuitSlot === 'psu'
                          ? 'bg-rose-900/60 border-rose-500 scale-102 animate-wiggle'
                          : showHint && selectedConveyorItem === 'psu'
                          ? 'border-dashed border-amber-400 bg-amber-500/20 ring-2 ring-amber-400/60 animate-pulse shadow-lg shadow-amber-500/30'
                          : selectedConveyorItem
                          ? 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500 hover:bg-slate-850'
                          : 'border-dashed border-slate-700 bg-slate-900/80 hover:border-slate-500'
                      }`}
                    >
                      {showHint && selectedConveyorItem === 'psu' && (
                        <span className="absolute -top-2.5 right-3 px-2 py-0.5 rounded-full bg-amber-500 text-slate-950 text-[9px] font-black uppercase tracking-wider animate-bounce shadow-md">
                          💡 Aici!
                        </span>
                      )}
                      <div className="flex items-center gap-2">
                        <span className="text-lg">{placedSlots.psu ? '🔌' : '⚡'}</span>
                        <div className="text-left">
                          <div className="text-[11px] font-bold text-white">Compartiment Sursă</div>
                          <div className="text-[9px] font-mono text-rose-300">
                            {placedSlots.psu ? '✅ Cablu 24-Pin Conectat' : 'Alimentare 750W'}
                          </div>
                        </div>
                      </div>
                      <span className="text-[8px] font-mono text-slate-400">ATX PSU</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>

              {/* Power-On Boot Master Button */}
              <div className="mt-4 pt-3 border-t border-slate-800 flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3">
                <div className="text-xs text-slate-400 font-mono text-center sm:text-left">
                  {isAllPlaced ? (
                    <span className="text-emerald-400 font-bold flex items-center justify-center sm:justify-start gap-1.5">
                      <Sparkles className="w-4 h-4 shrink-0" />
                      Toate componentele sunt montate! Apasă butonul de pornire!
                    </span>
                  ) : (
                    <span>Alege o piesă de pe bandă și atinge slotul ei corespunzător.</span>
                  )}
                </div>

                <button
                  onClick={startBootSequence}
                  disabled={!isAllPlaced || isBooting || isBootSuccess}
                  className={`w-full sm:w-auto px-6 py-3 rounded-2xl font-black text-xs sm:text-sm transition flex items-center justify-center gap-2 cursor-pointer shadow-lg active:scale-95 ${
                    isAllPlaced && !isBootSuccess
                      ? 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-slate-950 shadow-emerald-500/30 animate-pulse'
                      : isBootSuccess
                      ? 'bg-emerald-600/30 text-emerald-400 border border-emerald-500/30 cursor-default'
                      : 'bg-slate-800 text-slate-500 cursor-not-allowed opacity-50'
                  }`}
                >
                  <Power className="w-4 h-4 shrink-0" />
                  <span>{isBooting ? 'Secvență POST...' : isBootSuccess ? 'PC Pornit (POST OK) ✅' : 'POWER ON (Bootează) 🟢'}</span>
                </button>
              </div>

              {/* Boot Terminal Log View */}
              {bootLog.length > 0 && (
                <div className="mt-4 p-4 rounded-2xl bg-black/90 border border-emerald-500/40 text-xs font-mono text-emerald-300 flex flex-col gap-1.5 animate-fadeIn">
                  <div className="flex items-center justify-between text-slate-400 border-b border-slate-800 pb-1 mb-1 text-[10px]">
                    <span>BIOS / UEFI POST System Diagnostics Log</span>
                    <span className="animate-pulse text-emerald-400">ONLINE</span>
                  </div>
                  {bootLog.map((line, idx) => (
                    <div key={idx} className="leading-relaxed">
                      {line}
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Right: Component Conveyor Belt & Hardware Inspector */}
            <div className="lg:col-span-4 flex flex-col gap-4">
              {/* Conveyor Belt / Warehouse Tray */}
              <div className="p-4 rounded-3xl bg-slate-950 border-2 border-slate-800 flex flex-col gap-3 shadow-md">
                <div className="flex items-center justify-between text-xs font-mono font-bold text-slate-300 uppercase tracking-wider">
                  <span className="flex items-center gap-1.5">
                    <Wrench className="w-4 h-4 text-blue-400" />
                    Banda Rulantă:
                  </span>
                  <div className="flex items-center gap-2">
                    <button
                      type="button"
                      onClick={handleToggleHint}
                      title={lang === 'en' ? 'Show where component fits' : 'Arată unde se montează piesa selectată'}
                      className={`px-2.5 py-1 rounded-xl text-[11px] font-bold font-mono transition flex items-center gap-1 cursor-pointer border active:scale-95 ${
                        showHint
                          ? 'bg-amber-500 text-slate-950 border-amber-400 animate-pulse shadow-md shadow-amber-500/20'
                          : 'bg-amber-500/15 hover:bg-amber-500/25 text-amber-300 border-amber-500/40'
                      }`}
                    >
                      <Lightbulb className={`w-3.5 h-3.5 ${showHint ? 'text-slate-950' : 'text-amber-400'}`} />
                      <span>{showHint ? (lang === 'en' ? 'Hide Hint' : 'Ascunde') : (lang === 'en' ? 'Hint' : '💡 Indiciu')}</span>
                    </button>
                    <span className="text-blue-400 text-[11px]">
                      {conveyorItems.length} rămase
                    </span>
                  </div>
                </div>

                {conveyorItems.length === 0 ? (
                  <div className="p-6 rounded-2xl bg-emerald-950/30 border border-emerald-500/30 text-center flex flex-col items-center justify-center gap-2">
                    <CheckCircle2 className="w-8 h-8 text-emerald-400 animate-bounce" />
                    <span className="text-xs font-bold text-emerald-300">
                      Bancul de lucru este gol! Toate piesele au fost montate!
                    </span>
                  </div>
                ) : (
                  <div className="flex flex-col gap-2 max-h-[380px] overflow-y-auto pr-1">
                    {conveyorItems.map((compKey) => {
                      const comp = ALL_COMPONENTS[compKey];
                      const isSelected = selectedConveyorItem === compKey;

                      return (
                        <button
                          key={comp.id}
                          type="button"
                          onClick={() => {
                            sounds.playClick();
                            setSelectedConveyorItem(isSelected ? null : compKey);
                            setHoveredComponent(comp);
                            setShowHint(false);
                          }}
                          onMouseEnter={() => setHoveredComponent(comp)}
                          className={`p-3 rounded-2xl border-2 text-left transition-all flex items-center justify-between gap-3 cursor-pointer active:scale-95 ${
                            isSelected
                              ? 'bg-blue-600 text-white border-blue-300 ring-2 ring-blue-400/50 shadow-lg scale-102'
                              : 'bg-slate-900/90 hover:bg-slate-850 text-slate-200 border-slate-800 hover:border-slate-700'
                          }`}
                        >
                          <div className="flex items-center gap-2.5">
                            <span className="text-2xl">{comp.icon}</span>
                            <div>
                              <div className="text-xs font-bold leading-tight">{comp.nameRo}</div>
                              <div className="text-[10px] font-mono text-slate-400 mt-0.5">
                                {comp.categoryRo}
                              </div>
                            </div>
                          </div>
                          <ChevronRight className={`w-4 h-4 shrink-0 transition-transform ${isSelected ? 'rotate-90 text-white' : 'text-slate-500'}`} />
                        </button>
                      );
                    })}
                  </div>
                )}

                <div className="text-[11px] text-slate-400 font-mono italic flex items-start gap-1.5">
                  <span className="shrink-0">💡</span>
                  <span>
                    Fă click pe o piesă de pe bandă, apoi alege slotul pe placa de bază. Apasă pe <strong>Indiciu</strong> dacă ai nevoie de ajutor!
                  </span>
                </div>
              </div>

              {/* Hardware Inspector / Didactic Info Box */}
              <div className="p-4 rounded-3xl bg-slate-950 border-2 border-slate-800 flex flex-col gap-2 shadow-md">
                <div className="flex items-center gap-1.5 text-xs font-mono font-bold text-slate-400 uppercase tracking-wider">
                  <Info className="w-3.5 h-3.5 text-cyan-400" />
                  <span>Fișă Tehnică Hardware:</span>
                </div>

                {hoveredComponent ? (
                  <div className="flex flex-col gap-2 animate-fadeIn text-xs">
                    <div className="font-bold text-white text-sm flex items-center gap-2">
                      <span>{hoveredComponent.icon}</span>
                      <span>{hoveredComponent.nameRo}</span>
                    </div>
                    <div className="text-emerald-400 font-mono text-[11px]">
                      {hoveredComponent.specsRo}
                    </div>
                    <p className="text-slate-300 text-xs leading-relaxed">
                      {hoveredComponent.descriptionRo}
                    </p>
                  </div>
                ) : (
                  <div className="text-slate-500 text-xs italic py-2">
                    Treci cu mouse-ul sau atinge o componentă de pe bandă pentru a-i citi rolul didactic în arhitectura calculatorului.
                  </div>
                )}

                {/* Didactic Tip for the current level */}
                <div className="mt-2 pt-2 border-t border-slate-800 text-[11px] text-amber-300 font-mono">
                  {currentLevel.bonusNoteRo}
                </div>
              </div>

              {/* Next Level Button (shown after successful boot) */}
              {isBootSuccess && currentLevelIdx + 1 < PC_BUILD_LEVELS.length && (
                <button
                  onClick={handleNextLevel}
                  className="p-4 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white font-black text-sm transition flex items-center justify-center gap-2 shadow-lg shadow-blue-600/30 cursor-pointer animate-bounce active:scale-95"
                >
                  <span>Nivelul Următor ➔</span>
                </button>
              )}
            </div>
          </div>

          {/* Game Over by Timeout Modal Overlay */}
          {isGameOverTimeout && (
            <div className="absolute inset-0 bg-slate-950/90 backdrop-blur-sm rounded-3xl flex flex-col items-center justify-center p-6 text-center gap-4 z-30 animate-fadeIn">
              <div className="w-16 h-16 rounded-2xl bg-rose-500/20 border border-rose-500/40 text-3xl flex items-center justify-center">
                ⏱️
              </div>
              <h3 className="text-xl sm:text-2xl font-black text-white font-heading">
                Timpul a Expirat!
              </h3>
              <p className="text-slate-300 text-xs sm:text-sm max-w-md">
                Banda rulantă s-a oprit înainte de a putea monta toate componentele pe placa de bază. Fii mai rapid la următoarea încercare!
              </p>
              <button
                onClick={initLevel}
                className="px-6 py-3 rounded-2xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-sm transition flex items-center gap-2 shadow-lg cursor-pointer active:scale-95"
              >
                <RotateCcw className="w-4 h-4" />
                <span>Reîncearcă Nivelul</span>
              </button>
            </div>
          )}
        </div>
      ) : (
        /* Final Victory Screen */
        <div className="bg-slate-900/95 border-2 border-blue-500/30 rounded-3xl p-6 sm:p-10 shadow-2xl flex flex-col items-center justify-center text-center gap-6">
          <div className="w-20 h-20 rounded-3xl bg-gradient-to-tr from-blue-500 to-indigo-600 flex items-center justify-center text-4xl shadow-xl shadow-blue-500/20 ring-4 ring-blue-500/20 animate-bounce">
            🖥️
          </div>

          <div>
            <span className="px-3.5 py-1 rounded-full bg-blue-500/20 text-blue-300 text-xs font-bold border border-blue-500/30 uppercase tracking-wider">
              {lang === 'en' ? 'Hardware Architect Diploma' : 'Certificat Inginer Hardware TIC'}
            </span>
            <h2 className="text-2xl sm:text-4xl font-black text-white font-heading mt-2">
              {studentName ? `${studentName}, ` : ''}
              {lang === 'en' ? 'Master PC Builder! 💻⚡' : 'Maestru în Arhitectura PC! 💻⚡'}
            </h2>
            <p className="text-slate-300 text-xs sm:text-sm max-w-lg mt-2">
              {lang === 'en'
                ? 'You successfully diagnosed, assembled, and booted all computer systems from basic office PCs to high-performance AI servers!'
                : 'Ai demonstrat cunoștințe temeinice de arhitectură hardware, asamblând și bootând cu succes toate sistemele de calcul din laborator!'}
            </p>
          </div>

          {/* Stats Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3.5 max-w-lg w-full">
            <div className="bg-slate-950/90 border border-slate-800 rounded-2xl p-4 flex flex-col items-center justify-center">
              <span className="text-xs text-slate-400 uppercase font-bold">Scor Total</span>
              <span className="text-3xl sm:text-4xl font-black text-blue-400 font-mono mt-1">
                {score}
              </span>
              <span className="text-[11px] text-slate-500">puncte</span>
            </div>

            <div className="bg-slate-950/90 border border-slate-800 rounded-2xl p-4 flex flex-col items-center justify-center">
              <span className="text-xs text-slate-400 uppercase font-bold">PC-uri Bootate</span>
              <span className="text-3xl sm:text-4xl font-black text-emerald-400 font-mono mt-1">
                {PC_BUILD_LEVELS.length} / {PC_BUILD_LEVELS.length}
              </span>
              <span className="text-[11px] text-slate-500">fără scurtcircuit</span>
            </div>

            <div className="bg-slate-950/90 border border-slate-800 rounded-2xl p-4 flex flex-col items-center justify-center">
              <span className="text-xs text-slate-400 uppercase font-bold">Competență TIC</span>
              <span className="text-sm font-black text-amber-400 font-mono mt-1 text-center">
                Hardware & POST
              </span>
              <span className="text-[11px] text-slate-500">asamblare practică</span>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-3">
            <button
              onClick={handleRestartWholeGame}
              className="px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-sm transition flex items-center gap-2 shadow-lg shadow-blue-600/30 cursor-pointer active:scale-95"
            >
              <RotateCcw className="w-4 h-4" />
              <span>{lang === 'en' ? 'Play Again' : 'Asamblează din Nou'}</span>
            </button>
            <button
              onClick={() => {
                sounds.playClick();
                onBack();
              }}
              className="px-6 py-3 rounded-2xl bg-slate-800 hover:bg-slate-750 text-slate-200 font-bold text-sm transition border border-slate-700 cursor-pointer"
            >
              <span>{lang === 'en' ? 'Back to Arcade' : 'Înapoi la Jocuri'}</span>
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
